### ISSUE TITLE
From GTEx IDs to SRX IDs

### ISSUE THREAD

**Issue by mimiblis** [BgeeDB/expression-annotations#101]
To make the pipeline run correctly we need SRX IDs for each samples. 
To make this possible, I implemented Python scripts to:
1. Retrieve the GTEx ID's for the samples we annotated
2. On the rxtx (file : SraRunTable_SRA_data_10-07-2015), I could match the GTEx ID's for the sample of interest with their corresponding SRR ID's
3. On these page (http://www.ebi.ac.uk/ena/data/view/SRP012682) I could match the SRR ID's to SRX ID's
--> this is were I saw that only RNAseq samples have SRX ID's, thus that I discovered that in the GTEx sample file, there are mix of RNAseq, affy, illuminaOmni samples

**Comment by mimiblis** [comment]
@ANiknejad : is it well enough explained? or do you need more details ? :-)

**Comment by ANiknejad** [comment]
Great! Many thanks!

Then we can link this issue to issue #98  because we see in 
http://www.ebi.ac.uk/ena/data/view/SRP012682 
that SRX Illumina are not all 'Illumina HiSeq 2000' but also 'Illumina MiSeq'

**Comment by mimiblis** [comment]
Ohhhh... So the platform is to correct for some of the samples? Sorry I did not notice this before

**Comment by ANiknejad** [comment]
yes please do, following the check done by Julien in issue 98

**Comment by mimiblis** [comment]
+1

**Comment by julien-roux** [comment]
> To make this possible, I implemented Python scripts to:
1. Retrieve the GTEx ID's for the samples we annotated

@mimiblis: I do not see this script on GitHub. Where is it located? If it's not there, it should be added.
> 2. On the rxtx (file : SraRunTable_SRA_data_10-07-2015), I could match the GTEx ID's for the sample of interest with their corresponding SRR ID's

The first colum of this file (`Assay_Type_s`) should be parsed by the script because it tells if the sample is indeed RNA-seq
> 3. On these page (http://www.ebi.ac.uk/ena/data/view/SRP012682) I could match the SRR ID's to SRX ID's

Did you download the `SRP012682.txt` file on this page? Is this file on the GitHub project?
> --> this is were I saw that only RNAseq samples have SRX ID's, thus that I discovered that in the GTEx sample file, there are mix of RNAseq, affy, illuminaOmni samples

And a lot of whole genome sequencing (WGS) and exome sequencing (WXS) samples that have SRX IDs... Please update the script accordingly

**Comment by mimiblis** [comment]
well it's "live" python scripting, and noone ever told me to put the scripts on the git.
not only I, but also Amina did scripting for this GTEx annotations.... 
Yes I did download this file SRP012682.txt, I will put it on the git ASAP
@ANiknejad @fbastian @julien-roux we really need to discuss all this...  because the SraRunTable contains only RNAseq samples if I am not mistaking, whereas this phs000424.v6.pht002743.v6.p1.c1.GTEx_Sample_Attributes.GRU.txt contains all kind of libraries.
We did not use these files, for annotations, only at the end, when we saw the kind of problems of mixed libraries we had

**Comment by julien-roux** [comment]
> well it's "live" python scripting, and noone ever told me to put the scripts on the git.
not only I, but also Amina did scripting for this GTEx annotations....

Yes we need to discuss this, but for future GTEx release, I think tehse scripts should be pu on github, and documented
> Yes I did download this file SRP012682.txt, I will put it on the git ASAP

Thanks
> @ANiknejad @fbastian @julien-roux we really need to discuss all this... because the SraRunTable contains only RNAseq samples if I am not mistaking, 

No, it also contains WGS and WXS samples (at least), see first column/
> whereas this phs000424.v6.pht002743.v6.p1.c1.GTEx_Sample_Attributes.GRU.txt contains all kind of libraries.

Yes, this one contains even more libraries, i.e., non sequencing libraries (arrays etc)
> We did not use these files, for annotations, only at the end, when we saw the kind of problems of mixed libraries we had

yes this is something to improve for next GTEx releases

**Comment by mimiblis** [comment]
okok, I saw in SraRunTable ! sorry!
So I wont touch anything until final discussion except removing non rnaseq from rnaseqlibrary.tsv.
I have done my hour quota this week with that.
So next week big discussion :-)

**Comment by julien-roux** [comment]
> So I wont touch anything until final discussion except removing non rnaseq from rnaseqlibrary.tsv.

Good, thanks!

**Comment by ANiknejad** [comment]
closed because all topics referenced in other issues
