### ISSUE TITLE
annotator IDs

### ISSUE THREAD

**Issue by julien-roux** [BgeeDB/expression-annotations#102]
It would be useful to put information on the annotators somewhere (maybe it is somewhere but I couldn't find). In particular, would be nice to have a full name corresponding to annotator IDs, and an email?
I suggest to add this info to `https://github.com/BgeeDB/expression-annotations/blob/master/README.md`

**Comment by ANiknejad** [comment]
may I close the issue @julien-roux ?

**Comment by julien-roux** [comment]
Maybe you can add also Frederic, Sebastien and me, since we may have to modify or correct some things?
What about past annotators (Aurélie, etc)? Are their initials anywhere in the annotation files? If so, I would add them.

**Comment by ANiknejad** [comment]
ok, I thought, some of the abbreviation were too much cryptic ;-) Will do

**Comment by mimiblis** [comment]
like me being a donkey (ANE) hihihihi

**Comment by fbastian** [comment]
I also updated the README, closing the issue.
