### ISSUE TITLE
GTEx samples - mix affy and RNAseq samples - how to separate?

### ISSUE THREAD

**Issue by mimiblis** [BgeeDB/expression-annotations#103]
As the title says from itself, GTEx samples are not only RNAseq as we thought, but also affymetrix data and others.
I saw this when I tried to convert the GTEx ID's into SRX ID's. 
I was told to use SraRunTable_SRA_data_10-07-2015.txt file from the rxtx + this link http://www.ebi.ac.uk/ena/data/view/SRP012682 to make the conversion.
So with Python scripts (see #101), I first looked into the SraRunTable file to convert GTEx ID's into SRR ID's. Here I already saw that some of the GTEx ID's were not to find in this file. 
Getting my brain to work, I went on the rxtx, and in this file phs000424.v6.pht002743.v6.p1.c1.GTEx_Sample_Attributes.GRU.txt, I was able to see that the GTEx ID's that did not match in the SraRunTable were whether affy data, or illumina omni SNP or illumina exome SNP data.
So what I did is simple:
1. GTEx ID's with a match in SraRunTable are effectively RNAseq and were converted into SRX and and are know in RNAseqLibrary.tsv + in /expression-annotations/annotations/gtex/final_annotations_categorized_by_type_of_exp/rnaseqGTEX_SRX.tsv
2. other GTEx samples (that we found were "good" samples), are to find in /expression-annotations/annotations/gtex/final_annotations_categorized_by_type_of_exp/ in 3 different files (affy, omni, exome)
3. but as Julien found in issue #106, in these "RNAseq libraries" there are still WGS and WXS mixed in it, so we cannot put these in rnaseqexperiment.tsv
4. on the page http://www.ebi.ac.uk/ena/data/view/SRP012682 , we have the possibilities, using "library_source" to know wherefrom is the library, so whether its rnaseq (transcriptomic) or WGS and WXS.

!!!! THE TYPE OF LIBRARY FOR EACH SAMPLE IS TO FIND IN phs000424.v6.pht002743.v6.p1.c1.GTEx_Sample_Attributes.GRU.txt, !!!!

**Comment by mimiblis** [comment]
related to this issue:
@ANiknejad : on monday you asked me to put the uberon mapping in the track file, so we know in one file whether the sample was included in bgee or not, and what are the difference in the mapping between us and GTEx.
- in this samples_track file, there are all samples (11200 something), this means there are also the ones Affy, Omni and Exome...
- how should I process? do you want me to add columns for which I will precise the "kind" of sample (e.g rnaseq, affy...) and then the mapping gtex and bgee for the samples tagged as "good"
- or do you want to keep only the rnaseq samples in this track file?
THANK YOU (and sorry for all these issues, I realize I have opened and asked you a lot today )

**Comment by julien-roux** [comment]
> 4. on the page http://www.ebi.ac.uk/ena/data/view/SRP012682 , we have the possibilities, using "library_source" to know wherefrom is the library, so whether its rnaseq (transcriptomic) or WGS and WXS.

I don't see this information in this file
> !!!! THE TYPE OF LIBRARY FOR EACH SAMPLE IS TO FIND IN phs000424.v6.pht002743.v6.p1.c1.GTEx_Sample_Attributes.GRU.txt, !!!!

Sorry again there is no unequivocal column in this file I think
Please have a look at the first column of the `SraRunTable_SRA_data_10-07-2015.txt` file from the rxtx instead

**Comment by julien-roux** [comment]
> 4. on the page http://www.ebi.ac.uk/ena/data/view/SRP012682 , we have the possibilities, using "library_source" to know wherefrom is the library, so whether its rnaseq (transcriptomic) or WGS and WXS.

I don't see this information in this file
> !!!! THE TYPE OF LIBRARY FOR EACH SAMPLE IS TO FIND IN phs000424.v6.pht002743.v6.p1.c1.GTEx_Sample_Attributes.GRU.txt, !!!!

Sorry again there is no unequivocal column in this file I think
Please have a look at the first column of the `SraRunTable_SRA_data_10-07-2015.txt` file from the rxtx instead

**Comment by ANiknejad** [comment]
@mimiblis 
could you please modify the file 'GTEx_samples-track.tsv' and create a new column (name 'Assay_Type_s_SraRunTable')  with information from the first column ('Assay_Type_s') of file 'SraRunTable_SRA_data_10-07-2015.txt' for those sample where information is available (see below difference between files) ?

**If you feel it is too messy to do, please tell us!**

11'983 samples are present in 'GTEx_samples-track.tsv' (checked, this is the correct original number of GTEx samples) while file 'SraRunTable_SRA_data_10-07-2015.txt' only contains information for 10'474 samples

**Comment by mimiblis** [comment]
@ANiknejad : I already added the type of library (TrueSeq = RNAseq, WGS...) won't it be redundant then?

**Comment by ANiknejad** [comment]
No, the current information is not a controlled vocabulary (CV)  information, with lot of inaccurate terms

**Comment by mimiblis** [comment]
okay, so I add the column from SRArunTAble, but what for the other types of samples? Affy, OMNI or else?
OR do you want me to "translate" the library status from phs000424.v6.pht002743.v6.p1.c1.GTEx_Sample_Attributes.GRU.txt?
what I mean is f.E: 
- TrueSeq becomes RNAseq and so on

**Comment by ANiknejad** [comment]
no no! just to report the first column of SraRunTable_SRA_data_10-07-2015.txt into the GTEx_samples-track.tsv for each sample. Put NA for those they will miss the information

**Comment by mimiblis** [comment]
okay, and I remove the other column :-)

**Comment by ANiknejad** [comment]
no please, do not remove the other column, just add a new one

**Comment by mimiblis** [comment]
hihihi okay ;-)

**Comment by ANiknejad** [comment]
closed so far
