### ISSUE TITLE
RNA-seq libraries that are not RNA-seq...

### ISSUE THREAD

**Issue by julien-roux** [BgeeDB/expression-annotations#106]
I added a step in my script to control that there is indeed confirmation that a sample is RNA-seq in the SRA record (the tag is `<LIBRARY_STRATEGY>`), and it appeared that a lot are not... 
* GSE38397: all 147 libraries need to be removed, they are DNA-seq.
* SRX534846 and SRX534847. These are annotated as ChIP-seq. But please check carefully since the GEO records seem quite messy and I saw "RNA-seq" indicated too in plain text fields.
* Sorry, this one will make you scream :scream: ! **A lot of GTEx annotated libraries are not RNA-seq**, but WXS ("Random exon sequencing", see http://www.ebi.ac.uk/ena/submit/reads-library-strategy, **392 libraries**) or WGS (Whole genome shotgun sequencing, **107 libraries**).

**Comment by mimiblis** [comment]
Damn it..... Thank you for the id's it will be then easier to clean.

**Comment by julien-roux** [comment]
This is what I have for now (the script is still running, but doesn't seem to find more, keep you fingers crossed)
SRX1151221	WXS
SRX1153220	WGS
SRX1154348	WGS
SRX1153724	WXS
SRX1151413	WXS
SRX1153862	WXS
SRX557566	WXS
SRX557564	WXS
SRX629182	WXS
SRX557235	WXS
SRX1152337	WXS
SRX1151941	WGS
SRX1152164	WXS
SRX1153546	WGS
SRX1144079	WGS
SRX556836	WXS
SRX556971	WXS
SRX557415	WXS
SRX1144136	WXS
SRX1155962	WGS
SRX1144127	WGS
SRX1151893	WXS
SRX1155943	WXS
SRX617916	WXS
SRX557647	WXS
SRX1152214	WXS
SRX1153856	WXS
SRX1154270	WGS
SRX1153137	WGS
SRX1152771	WXS
SRX594353	WXS
SRX613153	WXS
SRX1156034	WXS
SRX1156171	WXS
SRX1152458	WGS
SRX1153143	WXS
SRX1156070	WGS
SRX1152399	WXS
SRX557133	WXS
SRX1155723	WGS
SRX1153845	WXS
SRX556806	WXS
SRX1153612	WGS
SRX1151228	WXS
SRX556817	WXS
SRX1153063	WXS
SRX1152165	WXS
SRX1151873	WXS
SRX1152938	WGS
SRX1151474	WXS
SRX1152222	WXS
SRX1151741	WXS
SRX557366	WXS
SRX1154213	WXS
SRX1153311	WGS
SRX557169	WXS
SRX1153438	WGS
SRX1152114	WXS
SRX1151081	WXS
SRX557005	WXS
SRX1152404	WXS
SRX1153274	WXS
SRX1151283	WXS
SRX1150396	WXS
SRX1155985	WXS
SRX1151087	WXS
SRX1152575	WGS
SRX1153091	WGS
SRX1144124	WXS
SRX598257	WXS
SRX556942	WXS
SRX1152122	WGS
SRX1153013	WXS
SRX1153533	WXS
SRX557014	WXS
SRX1153359	WXS
SRX1152472	WXS
SRX1153357	WGS
SRX1152877	WXS
SRX1152484	WXS
SRX557570	WXS
SRX1153544	WGS
SRX557904	WXS
SRX557229	WXS
SRX1152853	WXS
SRX1149642	WGS
SRX1151888	WGS
SRX1153291	WGS
SRX1156096	WXS
SRX1156074	WXS
SRX557058	WXS
SRX575845	WXS
SRX557306	WXS
SRX1153711	WXS
SRX1153427	WGS
SRX1153431	WXS
SRX557050	WXS
SRX557444	WXS
SRX1143354	WXS
SRX1152732	WGS
SRX1153077	WGS
SRX1152244	WGS
SRX1153344	WXS
SRX557417	WXS
SRX557521	WXS
SRX556846	WXS
SRX1151884	WXS
SRX1152605	WXS
SRX1151340	WGS
SRX1151996	WXS
SRX557272	WXS
SRX1153801	WXS
SRX1151091	WGS
SRX1153536	WXS
SRX1151878	WGS
SRX1152560	WGS
SRX1156133	WGS
SRX1153521	WXS
SRX1153629	WXS
SRX557211	WXS
SRX557946	WXS
SRX556740	WXS
SRX1153260	WXS
SRX1150386	WXS
SRX573808	WXS
SRX1152812	WXS
SRX1153613	WXS
SRX1151999	WXS
SRX1152782	WXS
SRX556979	WXS
SRX1152676	WXS
SRX1153713	WXS
SRX1149646	WXS
SRX1153265	WXS
SRX1153282	WGS
SRX1150394	WGS
SRX1153284	WXS
SRX1153860	WXS
SRX557114	WXS
SRX556840	WXS
SRX1151776	WXS
SRX1153177	WGS
SRX1152720	WGS
SRX1153639	WGS
SRX1152451	WGS
SRX1152888	WGS
SRX1153340	WGS
SRX1150157	WXS
SRX1152105	WXS
SRX1153353	WXS
SRX1152573	WXS
SRX556857	WXS
SRX557476	WXS
SRX557115	WXS
SRX557472	WXS
SRX557562	WXS
SRX557189	WXS
SRX1151310	WXS
SRX1155653	WXS
SRX1153121	WGS
SRX1151854	WXS
SRX1153491	WXS
SRX1153074	WGS
SRX1153635	WGS
SRX1154216	WGS
SRX1152740	WXS
SRX1153661	WXS
SRX1142768	WXS
SRX557150	WXS
SRX557088	WXS
SRX558011	WXS
SRX557549	WXS
SRX563491	WXS
SRX1156037	WXS
SRX1153565	WXS
SRX1152671	WXS
SRX1152055	WGS
SRX1153722	WXS
SRX1153242	WGS
SRX1153498	WGS
SRX1151832	WGS
SRX1152779	WGS
SRX1152774	WGS
SRX1153081	WXS
SRX1152644	WXS
SRX1152727	WXS
SRX1151876	WXS
SRX1151306	WXS
SRX1152109	WXS
SRX1151774	WXS
SRX557973	WXS
SRX557349	WXS
SRX557195	WXS
SRX557124	WXS
SRX557644	WXS
SRX1153481	WXS
SRX1152367	WXS
SRX1153402	WXS
SRX1153507	WGS
SRX1151386	WGS
SRX1152947	WGS
SRX1154221	WGS
SRX1153508	WXS
SRX1154268	WXS
SRX1143351	WXS
SRX556801	WXS
SRX595088	WXS
SRX598791	WXS
SRX557138	WXS
SRX557516	WXS
SRX557031	WXS
SRX557358	WXS
SRX1153376	WXS
SRX1151997	WXS
SRX1155993	WGS
SRX1152279	WGS
SRX1152119	WGS
SRX1151418	WGS
SRX1151838	WXS
SRX558894	WXS
SRX556934	WXS
SRX556831	WXS
SRX615788	WXS
SRX1151360	WXS
SRX1150145	WXS
SRX1153125	WXS
SRX1152311	WGS
SRX1152669	WXS
SRX1153276	WGS
SRX1153136	WXS
SRX1153123	WGS
SRX1153608	WGS
SRX1144194	WGS
SRX1153250	WGS
SRX1156052	WGS
SRX1150392	WXS
SRX1151860	WXS
SRX1152745	WXS
SRX1144137	WXS
SRX1152104	WXS
SRX1153352	WXS
SRX1143569	WXS
SRX556757	WXS
SRX557443	WXS
SRX558458	WXS
SRX557708	WXS
SRX556737	WXS
SRX556952	WXS
SRX1150134	WXS
SRX1152642	WXS
SRX1152565	WXS
SRX1151836	WXS
SRX1153196	WXS
SRX1153527	WGS
SRX1151409	WXS
SRX1151833	WGS
SRX1154350	WGS
SRX1142770	WGS
SRX1155967	WXS
SRX1143573	WXS
SRX1153662	WXS
SRX1152482	WXS
SRX557168	WXS
SRX557685	WXS
SRX557661	WXS
SRX566728	WXS
SRX1152456	WXS
SRX1153483	WGS
SRX1150819	WGS
SRX1152474	WXS
SRX1152170	WXS
SRX1150155	WXS
SRX1151969	WXS
SRX1153272	WXS
SRX1156043	WXS
SRX1151770	WXS
SRX557397	WXS
SRX557489	WXS
SRX557457	WXS
SRX1153690	WXS
SRX1153095	WXS
SRX1151223	WGS
SRX1153505	WXS
SRX1155582	WGS
SRX1142720	WGS
SRX1155656	WXS
SRX1153270	WXS
SRX1142756	WXS
SRX1151364	WXS
SRX1152475	WXS
SRX557860	WXS
SRX557256	WXS
SRX1153443	WXS
SRX1152111	WXS
SRX1151452	WXS
SRX1156011	WXS
SRX1153430	WGS
SRX1152486	WXS
SRX1151881	WXS
SRX1155657	WXS
SRX1153247	WXS
SRX1153842	WXS
SRX1151614	WXS
SRX1153487	WXS
SRX1151337	WXS
SRX1152454	WGS
SRX1152517	WGS
SRX1152636	WGS
SRX1151947	WGS
SRX1151944	WXS
SRX1151717	WXS
SRX1151864	WXS
SRX1150149	WXS
SRX1153255	WXS
SRX557585	WXS
SRX557297	WXS
SRX556886	WXS
SRX556833	WXS
SRX1152542	WXS
SRX1144028	WXS
SRX1154263	WXS
SRX1151868	WXS
SRX1152221	WXS
SRX1152736	WXS
SRX1152882	WGS
SRX1155994	WXS
SRX1153060	WGS
SRX1155580	WGS
SRX1151367	WGS
SRX1152408	WXS
SRX1153381	WXS
SRX1153460	WXS
SRX1153092	WXS
SRX1153245	WXS
SRX1153347	WXS
SRX1151857	WXS
SRX1152115	WXS
SRX1156149	WXS
SRX556769	WXS
SRX557650	WXS
SRX576206	WXS
SRX1152512	WXS
SRX1152308	WGS
SRX1151611	WXS
SRX1152369	WGS
SRX1144217	WGS
SRX1144128	WGS
SRX1153267	WXS
SRX1153462	WXS
SRX1152555	WXS
SRX1150152	WXS
SRX557391	WXS
SRX556791	WXS
SRX596123	WXS
SRX601854	WXS
SRX1153262	WXS
SRX1152398	WGS
SRX1151748	WGS
SRX1152734	WXS
SRX1153096	WXS
SRX1153511	WXS
SRX1153575	WXS
SRX1150816	WXS
SRX1153478	WXS
SRX1142766	WXS
SRX614670	WXS
SRX600663	WXS
SRX557049	WXS
SRX1152632	WXS
SRX1151827	WXS
SRX1153541	WXS
SRX1152058	WXS
SRX1152251	WGS
SRX1152572	WXS
SRX1151412	WGS
SRX1153379	WXS
SRX1151083	WXS
SRX1151451	WXS
SRX1153059	WXS
SRX1152892	WXS
SRX1153858	WXS
SRX1151851	WXS
SRX557327	WXS
SRX556875	WXS
SRX1152784	WXS
SRX1153867	WGS
SRX1151257	WXS
SRX1155987	WXS
SRX1151840	WXS
SRX1152257	WXS
SRX1152561	WXS
SRX1152286	WXS
SRX582786	WXS
SRX1156048	WGS
SRX1151712	WXS
SRX1153797	WXS
SRX1151363	WXS
SRX1152915	WXS
SRX1143559	WXS
SRX1152666	WXS
SRX1151861	WXS
SRX1152874	WXS
SRX1156046	WXS
SRX1153490	WXS
SRX1153500	WXS
SRX629885	WXS
SRX557179	WXS
SRX1151498	WXS
SRX1152406	WXS
SRX1152568	WXS
SRX1144214	WXS
SRX1153605	WGS
SRX1153217	WXS
SRX1152374	WGS
SRX1152255	WXS
SRX1153342	WXS
SRX1156128	WXS
SRX557158	WXS
SRX1151407	WXS
SRX1152967	WXS
SRX1153176	WXS
SRX1152569	WXS
SRX1151261	WXS
SRX1152402	WXS
SRX1155921	WXS
SRX1153568	WXS
SRX1152028	WXS
SRX1152679	WXS
SRX1153688	WXS
SRX562052	WXS
SRX1152730	WXS
SRX1156101	WXS
SRX1156101	WXS
SRX1156101	WXS
SRX1156101	WXS
SRX1156101	WXS
SRX1156101	WXS
SRX1156101	WXS
SRX1156101	WXS
SRX1153464	WXS
SRX1150147	WXS
SRX1156042	WXS
SRX1144121	WGS
SRX1153469	WGS
SRX1152680	WXS
SRX1152807	WXS
SRX1156071	WXS
SRX1152365	WXS
SRX1153523	WXS
SRX1144026	WXS
SRX1151973	WXS
SRX606373	WXS
SRX557055	WXS
SRX559104	WXS
SRX1151896	WXS
SRX1152541	WXS
SRX1144160	WGS
SRX1151334	WXS
SRX1143356	WGS
SRX1153192	WGS
SRX1155963	WGS
SRX1153362	WGS
SRX1152333	WGS
SRX1152161	WXS
SRX1153268	WXS
SRX1152194	WXS
SRX1152884	WXS
SRX1151882	WXS
SRX1152750	WXS
SRX560998	WXS
SRX565859	WXS
SRX556827	WXS
SRX557217	WXS
SRX557203	WXS
SRX1151308	WXS
SRX1153572	WGS
SRX1153127	WXS
SRX1153534	WXS
SRX1151743	WXS
SRX1156099	WXS
SRX1155877	WXS
SRX1153539	WXS
SRX557101	WXS
SRX1152726	WXS
SRX1153518	WXS
SRX1152101	WXS
SRX1151085	WGS
SRX1152168	WXS
SRX1153011	WXS
SRX1152879	WXS
SRX1153314	WXS
SRX1152006	WXS
SRX1153014	WXS
SRX1151866	WXS
SRX557141	WXS

**Comment by julien-roux** [comment]
In addition to removing these GTEx libraries from `RNASeqLibrary.tsv`, I think it's worth investigating how comes these libraries were not removed before. You should really spot the place where the library type (library "strategy" in SRA) is indicated, for future annotation.

**Comment by mimiblis** [comment]
I do not know if you rememeber, but we already had issues with affy and illumina omni + exome, being mixed with the rnaseq samples... 
The main problem is, that in the raw sample file, GTEx mixed up every kind of library...
I first saw that there were some affy, omni and exome because these samples were not present in the SraRunTable for SRR and SRX conversion --> see issue #103.
Since WGS and WXS samples had corresponding SRX ID here : http://www.ebi.ac.uk/ena/data/view/SRP012682, they were taken as RNAseq
I will complete issue #103 to make it clearer.
+ @ANiknejad: please see my second comment of #103, because in the track file we did for all the samples, it might be good to signal also these WGS and WXS

**Comment by julien-roux** [comment]
I also commented on issues #101 and #103

**Comment by mimiblis** [comment]
GSE38397: all 147 libraries need to be removed, they are DNA-seq.
--DONE 73e199c
    SRX534846 and SRX534847. These are annotated as ChIP-seq. But please check carefully since the GEO records seem quite messy and I saw "RNA-seq" indicated too in plain text fields.
--
    Sorry, this one will make you scream :scream: ! A lot of GTEx annotated libraries are not RNA-seq, but WXS ("Random exon sequencing", see http://www.ebi.ac.uk/ena/submit/reads-library-strategy, 392 libraries) or WGS (Whole genome shotgun sequencing, 107 libraries).
--DONE a1a55bc

**Comment by mimiblis** [comment]
currently updating the "track-file" for WGS and WXS samples

**Comment by ANiknejad** [comment]
you really removed the SRX from the RNASeqLibrary.tsv??
why not just commented?
...because you had here a useful mapping GTEx sample/SRX

**Comment by mimiblis** [comment]
heum yes, but it's no RNAseq... anyway I have them still in this file: /expression-annotations/annotations/gtex/final_annotations_categorized_by_type_of_exp/rnaseqGTEX_SRX.tsv
so for the mapping in the track file, will be ok

**Comment by ANiknejad** [comment]
you mean, the GTEx_samples-track.tsv is not updated regarding this cleaning done in RNASeqLibrary.tsv?

**Comment by ANiknejad** [comment]
I guess, we need a new column in GTEx_samples-track.tsv to do the final sample acceptation in our annotation files regarding all the post-annotation check done for chip type

**Comment by mimiblis** [comment]
non, je la fais en français, c'est plus simple
- alors ou le track-file est updaté jusqu'au moment ou Julien a vu que rnaseqlibrary.tsv contenait des WGS/WXS
- donc j'ai supprimé du rnaseqlibrary tout ce qui n'est pas rnaseq (donc WGS et WXS)
- mais je n'ai pas fait le changement dans le fichier : /expression-annotations/annotations/gtex/final_annotations_categorized_by_type_of_exp/rnaseqGTEX_SRX.tsv
- donc pour le track-file, que je suis en train d'updater
  - on saura pour chaque sample si cest RNAseq ou WGS ou WXS
  - pour les samples qui ont un SRX (cf /expression-annotations/annotations/gtex/final_annotations_categorized_by_type_of_exp/rnaseqGTEX_SRX.tsv) --> je vais ajouter le SRX correspondant dans le track-file
- une fois cela fait, ainsi que le mapping uberon relevé, je vais enlever les samples WGS et WXS du /expression-annotations/annotations/gtex/final_annotations_categorized_by_type_of_exp/rnaseqGTEX_SRX.tsv et faire un fichier WGS-WXS comme il en existe un pour affy ou autre

**Comment by ANiknejad** [comment]
ok, il nous faut absolument un GTEx_samples-track.tsv à jour, et qui reporte les derniers nettoyages, donc n'hesite pas à ajouter des colonnes bien documentées par leur nom, pour montrer les étapes de ces rejets de samples post-annotation (du aux chip types donc)

**Comment by mimiblis** [comment]
oui pas de soucis. ce sera effectivment le fichier de référence et je vais y mettre le plus d'infos possible :-)

**Comment by ANiknejad** [comment]
masi je préfère que tu crées de nouvelles colonnes sans rien modifier/deleter avant, comme ca on sait qu'il faut lire la colonne la plus à droite pour avoir les infos à jour

**Comment by mimiblis** [comment]
oui --> bon dans ce fichier je n'ai rien a enlever donc c'est ok :-)

**Comment by ANiknejad** [comment]
oui. je voulais dire **ne pas modifier** la colonne B qui était l'acceptation des samples pour l'annotation

**Comment by mimiblis** [comment]
haaa! non de toute facon pas --> car si un jour fou vous faites du WGS ou WXS ou autre dans Bgee, ca vous arrangera d'avoir ces statuts hehe, puis chronologiquement dans le boulot GTEx c'est logique hihi

**Comment by ANiknejad** [comment]
peux-tu mettre aussi dans GTEx_samples-track.tsv ta correspondance SRX?

ANE: python scripts - from GTEx ID's to SRX ID's --> then put on the git (where?)

**Comment by mimiblis** [comment]
oui c'est prévu. cf pour les samples qui ont un SRX (cf /expression-annotations/annotations/gtex/final_annotations_categorized_by_type_of_exp/rnaseqGTEX_SRX.tsv) --> je vais ajouter le SRX correspondant dans le track-file
- par contre pour les python-scripts... je dois les mettre ou sur le git?

**Comment by fbastian** [comment]
@mimiblis please add you script into `utils/gtex/` as discussed.

**Comment by mimiblis** [comment]
erf, last time you told me you do not need scripts??!!!

**Comment by fbastian** [comment]
Just this one. When we discussed we decided that this one might be useful in the future (it's not awk command lines :p)

**Comment by mimiblis** [comment]
okay, will do by the end of the week ;P

**Comment by ANiknejad** [comment]
closed
