### ISSUE TITLE
Angelique's work until end of month 

### ISSUE THREAD

**Issue by mimiblis** [BgeeDB/expression-annotations#107]
This issue is modifiable by anyone, it's just so that everyone sees what I still have to do until the end of month, or if someone does something in the list, it would be nice to remove it hehe
- put the gtex and bgee uberon mapping in the track-file --  4edfef0 
- add a column for library in track-file (#103, last comments) -- d5ef169
- #106 - add column in track-file --> SRX + SRR for the sample possible -- d5ef169
- #105 - put affy-gtex in affyChip.tsv
  - so platform ok with  GPL16977??
  - ChIP ID? == GTEx ID or not?
  - experiment ID?
  - normalizationTypeId?
  - detectionTypeId?
- #106 
  - SRX534846 and SRX534847 chipseq or rnaseq?
- put SRP012682.txt on the git -- 4e07b7b
- #77
- #80 - RNAseq for @wirawara --> fine until end of February !

**Comment by ANiknejad** [comment]
>#80 - RNAseq for @wirawara --> fine until end of February !

After discussion with @fbastian and @wirawara, I will manage that

**Comment by mimiblis** [comment]
fddf264 --> will be updated according to track-file, when this one will be perfectly done. 
Need anyway answers from @ANiknejad (see first comment of this issue)

**Comment by ANiknejad** [comment]
closed
