### ISSUE TITLE
Complete conversion of GSM ids to SRX ids in RNASeqLibrary.tsv

### ISSUE THREAD

**Issue by smoretti** [BgeeDB/expression-annotations#111]
To make RNASeq downloads easier and more efficient, complete the conversion of **GSM ids** (from GEO) to **SRX (or ERX) ids** (from SRA) in *RNASeqLibrary.tsv*

Only some Drosophila modEncode samples remain:
http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE44612
'15 Drosophila species, including 8 previously unsequenced genomes'
125945  Drosophila biarmipes
42026    Drosophila bipectinata
30023    Drosophila elegans
29029    Drosophila eugracilis
30025    Drosophila ficusphila
30033    Drosophila kikkawai
1041015 Drosophila rhopaloa
29030    Drosophila takahashii

GSM1060482
GSM1060483
GSM1060484
GSM1060485
GSM1060486
GSM1060487
GSM1060488
GSM1060489
GSM1060490
GSM1060491
GSM1060492
GSM1060493
GSM1060494
GSM1060495
GSM1060496
GSM1060497
GSM1060498
GSM1060499
GSM1060500
GSM1060501
GSM1060502
GSM1060503
GSM1060504
GSM1060505
GSM1060506
GSM1060507

**Comment by ANiknejad** [comment]
GSM1060495
GSM1060496
--> both are SRX098564

GSM1060497
GSM1060498
--> both are SRX098565

So far I did not convert those 4 GSM, ...replicates? thoughts? @julien-roux

**Comment by smoretti** [comment]
They are replicates (i.e. Dfic_Male_replicate1 & Dfic_Male_replicate2 for respectively GSM1060497 & GSM1060498) with 2 SRR in their SRX.
How to deal with that?

Keep a single SRX entry in the annotation file but then we loose the replicate information.
Duplicate the SRX entry, the download will be done once, but duplication may introduce issues during database insertions.

@julien-roux & @fbastian ???

**Comment by fbastian** [comment]
We should keep one SRX, that will make the pipeline to download the two SRRs (pretty much equivalent to technical replicates)

**Comment by ANiknejad** [comment]
done
