### ISSUE TITLE
GSE63501

### ISSUE THREAD

**Issue by julien-roux** [BgeeDB/expression-annotations#115]
In my large-scale mapping test, 2 libraries from this experiment bugged. I checked and I saw that none of their reads were mapped. For other libraries of this experiment, only a few reads (~100) were mapped. This is because it is a miRNA-seq experiment, and while the miRNAs are ~22nt-long, the authors sequenced 51nt-long reads. Thus all reads contain adapter sequence and none could be mapped.

I suggest we comment out this experiment in the `RNASeqLibrary.tsv` file for now.
- Add a `#` at beginning of the line for the 7 libraries of this experiment
- Add this to comment field: `This is a miRNA-seq library, with 51nt-long reads. Thus all reads contain adapter sequences, which results in no or almost read read being mapped. It can be reintegrated if the pipeline is modified to trim adapter sequences before mapping.`

@ANiknejad can you take care of this?

**Comment by ANiknejad** [comment]
Done.
Thank you, Julien, for clear advices
