### ISSUE TITLE
RNASeqLibrary.tsv: correction of annotation TO DO

### ISSUE THREAD

**Issue by ANiknejad** [BgeeDB/expression-annotations#117]
GTEX-13PVQ-1926-SM-5L3GN
Muscularis of  lowest portion of esophagus;Esophagus - Gastroesophageal Junction
GTEX-145LS-2026-SM-5Q5D7
Muscularis of  lowest portion of esophagus;Esophagus - Gastroesophageal Junction
GTEX-ZYFG-1226-SM-5GIC7
Muscularis of  lowest portion of esophagus:Esophagus - Gastroesophageal Junction

These 3 samples are currently annotated on
UBERON:0004648	esophagus muscularis mucosa

However in RNASeqLibrary.tsv, samples with such information
Esophagus-Gastroesophageal Junction-Muscularis of lowest portion of esophagus

are correctly reannotated on
UBERON:0035841	esophagogastric junction muscularis propria

example:GTEX-11P82-0426-SM-5HL5D
Muscularis of  lowest portion of esophagus;Esophagus - Gastroesophageal Junction

**Comment by ANiknejad** [comment]
@aechchiki 
please consider that when you perform comparison between files, and please let me know when I can correct into RNASeqLibrary.tsv

**Comment by ANiknejad** [comment]
also
GTEX-XGQ4-1626-SM-4AT6J
in RNASeqLibrary.tsv, this sample has not the correct original information reported 

In the original file GTEx file, we have the description:
Squamous region, above gastroesophageal junction	Normal	Esophagus	Esophagus - Gastroesophageal Junction

which is not consistent (either 'above gastroesophageal junction' or 'Gastroesophageal Junction' but not both for the same sample description)

Due to this inconsistency for original sample description, I propose to remove (#comment) this sample, Fred, thoughts?
@fbastian

**Comment by fbastian** [comment]
Can't we annotate this sample to a common parent term?

**Comment by ANiknejad** [comment]
GTEX-ZPIC-1926-SM-57WFQ
this sample has the original GTEx information:
Mucosa;Esophagus - Gastroesophageal Junction

while in the current RNASeqLibrary.tsv 
it is
Esophagus-Gastroesophageal Junction-Muscularis of lowest portion of esophagus

and so the annotation is false:
should be 
UBERON:0035838 esophagogastric junction mucosa

instead of
UBERON:0035841	esophagogastric junction muscularis propria


@aechchiki 
I can do the correction once you have finish the check between files, please just let me know

**Comment by ANiknejad** [comment]
(I did check by filtring on the original GTEx sample file for the annotation they initially proposed, for instance 'UBERON:0004550 gastroesophageal sphincter')

**Comment by ANiknejad** [comment]
>fbastian commented 3 hours ago
Can't we annotate this sample to a common parent term?

why not indeed, we can annotate to UBERON:0001043 esophagus 
tag status 'other'

**Comment by ANiknejad** [comment]
@aechchiki 

could you please review this issue before considering things as finished?

**Comment by ANiknejad** [comment]
>GTEX-XGQ4-1626-SM-4AT6J

>

    fbastian commented 3 hours ago
    Can't we annotate this sample to a common parent term?

>why not indeed, we can annotate to UBERON:0001043 esophagus
tag status 'other'


@aechchiki

**Comment by ANiknejad** [comment]
>GTEX-ZPIC-1926-SM-57WFQ
this sample has the original GTEx information:
Mucosa;Esophagus - Gastroesophageal Junction

so to annotate on
UBERON:0035838 esophagogastric junction mucosa
@aechchiki

**Comment by ANiknejad** [comment]
(I discard a previous post, sorry for the mess)

Please see below (and also the post above)
@aechchiki 

All original GTEx annotation with 

UBERON:0004550
name: gastroesophageal sphincter

can be moved on
UBERON:0035841 esophagogastric junction muscularis propria

**Comment by ANiknejad** [comment]
GTEX-ZPIC-1926-SM-57WFQ
to annotate on 
UBERON:0001043 esophagus

due to inconsistent information between original columns for this sample:
6 pieces, all muscularis; GOODspecimens; adherent serosa on all, 1-2mm; rep foci delineated 
AND
mucosa

**Comment by aechchiki** [comment]
Hello, sorry for the late answer I was a bit busy :) 
so if I correctly understood, for esophagus samples, I need to reannotate ALL previously tagged "UBERON:0004550 - gastroesophageal sphincter" to "UBERON:0035841 - esophagogastric junction muscularis propria" EXCEPT sample GTEX-ZPIC-1926-SM-57WFQ, that has to be moved to "UBERON:0001043 - esophagus"

**Comment by ANiknejad** [comment]
>So if I correctly understood, for esophagus samples, I need to reannotate ALL previously tagged "UBERON:0004550 - gastroesophageal sphincter" to "UBERON:0035841 - esophagogastric junction muscularis propria" EXCEPT sample GTEX-ZPIC-1926-SM-57WFQ, that has to be moved to "UBERON:0001043 - esophagus"

AND also EXCEPT
GTEX-XGQ4-1626-SM-4AT6J (see in early post aboe)
to annotate to "UBERON:0001043 - esophagus"

**Comment by aechchiki** [comment]
> 

    So if I correctly understood, for esophagus samples, I need to reannotate ALL previously tagged "UBERON:0004550 - gastroesophageal sphincter" to "UBERON:0035841 - esophagogastric junction muscularis propria" EXCEPT sample GTEX-ZPIC-1926-SM-57WFQ, that has to be moved to "UBERON:0001043 - esophagus"

YES....
AND also EXCEPT
GTEX-XGQ4-1626-SM-4AT6J (see in early post aboe)
to annotate to "UBERON:0001043 - esophagus"


okay! c'est noté :)

**Comment by aechchiki** [comment]
@ANiknejad done: f871f149641ea1b04ee40cb6579739170a20fc3a

**Comment by ANiknejad** [comment]
great!
checked, ok!
