### ISSUE TITLE
Annotation issues in selected-samples (?)

### ISSUE THREAD

**Issue by aechchiki** [BgeeDB/expression-annotations#118]
I was going through (nth check) the annotations in the "clean"  version of selected-samples (aka the one without duplicates, and with only "YES" samples to be checked for quality), source for RNAseq final file. I might have noticed an imprecision in annotation for Thyroid samples (the imprecision is consistent in both selected-samples and RNAseq, this is why we haven't detected it automatically ;) ).

From the RNAseq Library file, it seems that in Bgee we are correcting the "universal" Uberon (UBERON:0002046 - thyroid gland) as proposed by GTEx this way:

- if both Left and Right thyroid: UBERON:0002046 - thyroid gland
- if only Left thyroid: UBERON:0001120 - left lobe of thyroid gland
- if only Right thyroid: UBERON:0001119 - right lobe of thyroid gland

If we only consider column SMSMPSTE (aka, tissue location), then the annotations in both selected-samples and RNAseq are correct. However, if we also consider column SMTSC (aka, free-text commentaries), then the annotations are not always correct. For example, sample `GTEX-X5EB-0726-SM-46MVR` has SMSMPSTE=="Non-nodular region" and SMTSC contains commentary "Left", which I interprete as that the sample is actually "Left thyroid" and not broad "thyroid". In this case, the annotation should be updated from current UBERON:0002046 (- thyroid gland) to UBERON:0001120 (- left lobe of thyroid gland).

I ask for @ANiknejad advice on my interpretations before an eventual annotation update.

**Comment by fbastian** [comment]
I propose to tag these annotations, for latter review, if this is too much work/too fussy information to make the correct annotations.

**Comment by aechchiki** [comment]
Actually, it's easy wok, I could re-annotate them right now! I just need Anne's green light :P

**Comment by ANiknejad** [comment]
yes, please Amina, it is exactly the kind of check and reasoning we need! 
I got the feeling that for some groups of sample, the information was lost due to Bgee consideration of the _GTEx Uberon as a tag for a common description of the samples_, which is **not** the case in fact (some samples with a different description were annotated the same by GTEx). See also example in  #117 where different samples were hidden behind GTEx original mapping 'UBERON:0004550 gastroesophageal sphincter'
So definitely, YES  and big THANKS!

**Comment by aechchiki** [comment]
Awesome, thanks! I will go through the annotation in selected-samples manually to check for similar issues. I will provide a list of the eventual changes ;)

**Comment by fbastian** [comment]
YOU are awesome @aechchiki!

**Comment by aechchiki** [comment]
@ANiknejad I didn't understand the annotation you decided to apply to "Kidney" tissue. 

For example, GTEX-UPIC-1126-SM-4IHLO (right kidney) is currently annotated on "left kidney better- UBERON:0004538 left kidney" in selected-samples - should be correct to update the annotation to "right kidney"? In RNAseqLibrary, organ information for this sample correctly reports "right kidney cortex". However, the final annotation maps to "UBERON:0001225	- cortex of kidney". Why not specify the precision right/left? 
Also, how come that kidneys in RNAseqLibrary are sometimes annotated as "UBERON:0000082 - adult mammalian kidney" and sometimes "UBERON:0001225	- cortex of kidney" when organ information reports exactly the same string (left kidney cortex in both cases)? And again, why not specifying the precision right/left? --- Note: if there's a particular reason for that, or if I have skipped some Issues while I was away from the Lab, please leave a comment here or cite the Issue so that I can update the Google Docs ;) 

[ @fbastian: caffeine in - annotation out :P ]

**Comment by ANiknejad** [comment]
Hi Amina @aechchiki 

please see issue #87 and #76

actually there is no left/right kidney cortex in Uberon, only kidney cortex.
Question is still open about accurate precise term for symmetric lateral sides. So far in our annotation files, human adult kidney is annotated on 'adult mammalian kidney' if no precise tissue is reported (cortex, medulla). Of course if you see an error in the annotation due to sample description not correctly reported in issue 76 or even missed, please open a issue for the sample and feel free to do the correction. And let me know if something is unclear.
Many thanks in advance

**Comment by aechchiki** [comment]
Okay, understood for kidney tissue, thanks ;)

I corrected some of the annotations following the advices reported in previous issues, I committed changes per tissue:
- thyroid: https://github.com/BgeeDB/expression-annotations/commit/38ab59201b6f5b0dcc458e680c9896537e6861fc
- cerebellum: https://github.com/BgeeDB/expression-annotations/commit/04057aa005af8ce2d5605d0320de2f4fe03c0f8c
- cerebral frontal pole: https://github.com/BgeeDB/expression-annotations/commit/133c0001e108064d98d0785ef73d3ce3c4f7a531
- kidney:https://github.com/BgeeDB/expression-annotations/commit/c0d427e74bc0a2359d57d3b5a7d99a3b5ccfc6de
- coronary artery: https://github.com/BgeeDB/expression-annotations/commit/9ffde27c72068ad89b988f7b65d8fc684d4d4668
- testis: https://github.com/BgeeDB/expression-annotations/commit/3db32825ace85161b25e0282dd3fe6228d8cc736

please refer to comments in each commit for changes details

**Comment by aechchiki** [comment]
About colon annotations, @ANiknejad:
- 1157	transverse colon -> accepted in Bgee
- 1159	sigmoid colon -> can be improved in Bgee:
  - if the sample contains "muscularis" only, then update to: UBERON:0035805 - muscle layer of sigmoid colon
  - if the sample does not contain "muscularis" only (usually referred to as "Curved portion of colon above rectum" in $D-SMSMPSTE, but better check $C- SMPTHNTS for keywords such as "mucosa", "serosa") then keep GTEx mapping: 1159 - sigmoid colon

Is this correct? If so, I found some annotation mistakes in selected-samples

**Comment by ANiknejad** [comment]
well spotted, Amina.

But in fact, if pathologists were following the instructions for colon here:

http://biospecimens.cancer.gov/resources/sops/docs/GTEx_SOPs/BBRB-PR-0004-W1%20GTEx%20Tissue%20Harvesting%20Work%20Instruction.pdf

they were supposed to collect:
- from transverse colon: mucosa and muscularis propria
- from sigmoid colon: muscularis propria

If we are not sure what they finally collect, so yes, better to annotate on the parent term, for instance
'sigmoid colon'

**Comment by aechchiki** [comment]
Ha, okay :) 

So, if I  understood correctly, for the moment, we leave the annotations for colon as proposed by GTEx, aka: 
- UBERON:0001157	transverse colon
- UBERON:0001159	sigmoid colon
 
So, should we reverse "UBERON:0035805 - muscle layer of sigmoid colon" as currently reported in RNAseq for sigmoid colon muscle samples to the original GTEx proposal?

**Comment by ANiknejad** [comment]
>from sigmoid colon: muscularis propria

I was not clear enough sorry!
all GTEx
1159	sigmoid colon 

can be reannotated safely on
UBERON:0035805
name: muscle layer of sigmoid colon
namespace: uberon
def: "A muscle layer that is part of the sigmoid colon" [https://github.com/obophenotype/uberon/issues/1162]
synonym: "muscularis externa of sigmoid colon" EXACT [FMA:15028]
synonym: "muscularis propria of sigmoid colon" EXACT []
synonym: "sigmoid colon muscularis propria" EXACT []

**Comment by ANiknejad** [comment]
>from transverse colon: mucosa and muscularis propria
I reviewed all samples and yes, to annotate on UBERON:0001157 transverse colon

exception with this sample:
GTEX-1399R-2226-SM-5P9JB	6 pieces; all contain only mucosa, no muscularis
--> to annotate oon
UBERON:0004991
name: mucosa of transverse colon

**Comment by ANiknejad** [comment]
DONE
thanks so much, Amina!
