### ISSUE TITLE
GSE41299 and discussion on short RNAs

### ISSUE THREAD

**Issue by mimiblis** [BgeeDB/expression-annotations#12]
- do not know if the strains are ok? annotated anyway, but do not know if strains are acceptable?
- technical replicates in the same strain?? that is what I think from the description

**Comment by aechchiki** [comment]
- All strains are listed in the "wild-type Zebrafish reference" (source: http://zfin.org/action/feature/wildtype-list ), thus I think they should all be acceptable :) 
- I also have issues to grab the exact replicate info...

**Comment by mimiblis** [comment]
commited as it is, just need more infos on the replicates, if it is possible to find some. After reading it again, I stay on my position, that per strain, there are tech replicates... but?

**Comment by ANiknejad** [comment]
From the paper: "To rule out the possibility that the observed differences are due to technical artifacts, we generated additional libraries of the ovaries of two Tu and two SJD individuals, which were also represented in the pooled libraries. "
So I guess, by strain, we have 3 biological replicates: 1X pool, 1x individu A, 1x individu B
Note that individus A and B are also in the pool of 5 individus (paper: "Since zebrafish strains have to be maintained outbred, we chose to sequence a pool of five individual males and females.)

Thoughts?

**Comment by mimiblis** [comment]
oui, mais si A fait partie du pool, alors cest un réplicat technique de lui même non?? Alors qu'il est réplicat biologique de B, C, D et E. cest bizarre dutiliser deux fois le meme individu dans deux sample.

**Comment by ANiknejad** [comment]
to check with Fred or Julien?

**Comment by fbastian** [comment]
Hmm, clearly they are not technical replicates, but there not **independent** biological replicates neither. If we wanted to be really safe, we could discard the "replicates", but I think it's OK to include them as biological replicates. I let Julien comment as well.

**Comment by julien-roux** [comment]
As I understand it (and I think that's what you got too), there are two libraries, the first made of 5 males (testes) and the second from 5 females (ovaries). Two additional libraries are made each from 1 female from the pool, so these are not independent replicates indeed. 
I would either keep the male and female pools, or the male pool + the 2 female biological replicates from different individuals.

Also, be careful, this is a small RNA sequencing library, targeted at short RNAs (< 30 nt). Do we include this type of library into Bgee?

**Comment by fbastian** [comment]
OK, so, let's stay on the safe side, and take the two pools only.

I think the Bgee pipeline is capable of processing short RNAs, as long as they correspond to an Ensembl gene model, don't you think so?

**Comment by julien-roux** [comment]
Sure, but I'm not clear about piRNAs in Ensembl:
http://www.ensembl.org/info/genome/genebuild/ncrna.html

**Comment by fbastian** [comment]
Well, in that case I guess that the worst scenario is simply that we won't have any data for those in Bgee.

**Comment by ANiknejad** [comment]
we already have such 'small RNA' in Bgee:

GSE38605	Genome-wide small RNA profiling and mRNA profiling of Xenopus embryos
GSE63501	Dysregulation of microRNAs in neurodegeneration

to check and remove?

@julien-roux 
@fbastian

**Comment by fbastian** [comment]
GSE63501 is not in the database, I guess it is annotated but not yet analyzed. 

GSE38605 is in the database, we have 3 libraries ('GSM946002', 'GSM946003', 'GSM946004'), statistics based on gene biotype: 

    +----------------------+---------------------------+--------------------+
    | geneBioTypeName      | count(distinct t2.geneId) | sum(t1.readsCount) |
    +----------------------+---------------------------+--------------------+
    | protein_coding       |                     18442 |            9544903 |
    | Mt_rRNA              |                         2 |              65951 |
    | miRNA                |                       333 |              29363 |
    | rRNA                 |                       270 |              24290 |
    | pseudogene           |                       121 |               7100 |
    | processed_pseudogene |                        52 |               1432 |
    | snRNA                |                       408 |                638 |
    | snoRNA               |                       224 |                277 |
    | misc_RNA             |                        47 |                243 |
    | Mt_tRNA              |                        22 |                  0 |

So, there is not much sXXX and miXXX, but at least there are some. The numbers seem reasonable to you @julien-roux?

**Comment by julien-roux** [comment]
Honestly I have no idea...
To compare we could look at number of hits on miRNAs in a normal RNA-seq library (in same species)?

**Comment by fbastian** [comment]
From experiment GSE37452, I took 3 libraries a about the same stages ('GSM919923', 'GSM919942', 'GSM919928'): 

    +----------------------+---------------------------+--------------------+
    | geneBioTypeName      | count(distinct t2.geneId) | sum(t1.readsCount) |
    +----------------------+---------------------------+--------------------+
    | protein_coding       |                     15232 |           21851232 |
    | Mt_rRNA              |                         2 |             331381 |
    | pseudogene           |                        66 |              24010 |
    | processed_pseudogene |                         6 |               6093 |
    | misc_RNA             |                        32 |                610 |
    | rRNA                 |                        20 |                598 |
    | snoRNA               |                        61 |                523 |
    | snRNA                |                        49 |                113 |
    +----------------------+---------------------------+--------------------+

miRNAs are absent despite the fact that there are twice as many reads mapped to protein coding genes, and sXXX are about the same.

So, seems convincing I guess @julien-roux?

**Comment by julien-roux** [comment]
But still it seems quite low in the sNRA RNA-seq library. 
Are miRNA genes intergrated into Bgee / used for mapping?

**Comment by ANiknejad** [comment]
The Kaessmman experience
http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE43520
also contains 3 samples 'smallRNA'
GSM1196058
GSM1196059
GSM1196060

to remove?
@fbastian 
@julien-roux

**Comment by ANiknejad** [comment]
'smallRNA' are ok for Bgee pipeline, Fred said during Monday weekly Bgee meeting

**Comment by ANiknejad** [comment]
@mimiblis 
@aechchiki 
For GSE41299, please consider Julien's and Fred's comments, and do the corrections
'two libraries, the first made of 5 males (testes) and the second from 5 females (ovaries).'
'let's stay on the safe side, and take the two pools only.'

and also check that GSE41299 is correctly reported in all the rna-seq files

**Comment by ANiknejad** [comment]
http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE41299
2 strains, SJD and Tu
2 cross progeny: TUxSJD AND SJDxTU
2 progeny, F1 and F2
all ovaries
plus testis for TU and for SJD
Total: 
2 strains X 2 tissues (1 pool male and 1 pool female) = 4
2 strains x 1 tissue (ovaries) x 2 sampling (2 indiv) = 4
2 cross-progeny X 2 generations (F1 and F2) x 3 sampling (1 pool + 2 indiv) = 12
= 20 samples (ok!)

Following Julien's advices, we conserve the male samples for the 2 strains
GSM1014086 	Tu Male
GSM1014087 	SJD male

and the 2 female individuals for the 4 strains (2 pure strains, and 2 cross-progeny SDJxTU and TUxSDJ at 2 generations, F1 and F2)

GSM1014069 	SJD P0 Individual 1
GSM1014070 	SJD P0 Individual 2
GSM1014072 	SJDxTuF1 Individual 1
GSM1014073 	SJDxTuF1 Individual 2
GSM1014075 	SJDxTuF2 Individual 1
GSM1014076 	SJDxTuF2 Individual 2
GSM1014078 	Tu P0 Individual 1
GSM1014079 	Tu P0 Individual 2
GSM1014081 	TuxSJDF1 Individual 1
GSM1014082 	TuxSJDF1 Individual 2
GSM1014084 	TuxSJDF2 Individual 1
GSM1014085 	TuxSJDF2 Individual 2

The 6 remaining samples are commented (#)

**Comment by julien-roux** [comment]
As we discussed last week (see also issue #119), the RNA-seq pipeline is currently no able to deal wiht small RNA libraries. 

I still suggest to annotate this experience, add it to `RNASeqLibrary.tsv`, but comment it with `#` at the beginning of the lines. Iw ould be nice to mention in the annotators comments that the reason for exclusion is that this is piRNA library.

It would be nice to go over this whole issue and spot the few other miRNA experiments mentioned, to comment them out too.

Thanks!

**Comment by ANiknejad** [comment]
Please tell me if you agree:
I totally discarded  (means, annotation is done but the lines are commented # with an explanations in column 'comments'):

GSE41299 
GSE38605
GSE63501 (was already commented with mention of reason)

then only these libraries from GSE43520
SRX328089 (=GSM1196058)
SRX328090 (=GSM1196059)
SRX328091 (=GSM1196060)

**Comment by julien-roux** [comment]
> Please tell me if you agree:
I totally discarded (means, annotation is done but the lines are commented # with an explanations in column 'comments'):
GSE41299
GSE38605
GSE63501 (was already commented with mention of reason)
then only these libraries from GSE43520
SRX328089 (=GSM1196058)
SRX328090 (=GSM1196059)
SRX328091 (=GSM1196060)

It looks good, thanks!
I'm closing the issue
