### ISSUE TITLE
RNASeq.tsv  on master - errors in GTEx stage annotation

### ISSUE THREAD

**Issue by ANiknejad** [BgeeDB/expression-annotations#123]
GTEX-1477Z-0011-R10b-SM-5S2RF

SRX591512	SRP012682	Illumina HiSeq 2000			UBERON:0009834	dorsolateral prefrontal cortex	HsapDv:0000161	65-year-old human stage

id: HsapDv:0000161
name: 67-year-old human stage

**Comment by ANiknejad** [comment]
please check the original file for the subject age!

**Comment by ANiknejad** [comment]
done

**Comment by fbastian** [comment]
Do we know how this error happened @aechchiki? Because the mapping to life stages was done automatically by a script, right?

**Comment by aechchiki** [comment]
will check it as the RNAseqLibrary annotation file is filled.

**Comment by ANiknejad** [comment]
It is important that the original information was correct, indeed. For mapping I guess, it sounds like the information was copy/past from previous samples just above having the information for age 67, while this sample was : age 65
