### ISSUE TITLE
Biocuration 2016, poster

### ISSUE THREAD

**Issue by ANiknejad** [BgeeDB/expression-annotations#127]
https://www.isb-sib.ch/events/biocuration2016/posters
number 104
Transcriptomics big data curation, sharing and re-analysis challenges: example of GTEx data integration into Bgee

here a draft

[draft_biocuration_2016.pptx](https://github.com/BgeeDB/expression-annotations/files/195097/draft_biocuration_2016.pptx)

@aechchiki 
please go further...;-)

@fbastian 
please comment and define text/figure area for stuff other than 'annotation'

**Comment by aechchiki** [comment]
@ANiknejad okay I will put there some ideas. is the google docs now considered as validated, aka can I take it as reference? also, my software (WPS) displays the ppt with some minor shifts, we may meet on Monday after 11h (or tomorrow, I'm available all day?) and make the modifications directly on your PC?

@fbastian if you have the time to list me some key points for analysis following annotation, I can check them before Bioc2016 and eventually be ready for some questions beyond annotation duties?

And, just an administrative question, do we receive the tickets for the conference or it will be on place? And we have to be there from April 11 to April 14 all day, right? Thanks

**Comment by ANiknejad** [comment]
@aechchiki 
ok for the google doc, as fas as I read it currently
here again the link for @fbastian 
https://docs.google.com/document/d/1IuNu3WGTSIhXnJffP_yo7lK2abSgxZQDPJgG1SYF5vI/edit?pli=1
for the poster: no worries, use your own ppt format (the one attached is .pptx just to match github requirements for attachment format), at the end we will convert to pdf anyway

**Comment by aechchiki** [comment]
I had an idea to "lighten" the poster visuals, don't know if it's good:

![img_20160330132624](https://cloud.githubusercontent.com/assets/13200013/14140737/27b07ed2-f67b-11e5-8d57-c96ff8b6892b.jpg)

**Comment by ANiknejad** [comment]
Great! But needs anyway explanation, specially for the 2 first steps, I guess
Also please see issue #116 for reannotation examples

**Comment by aechchiki** [comment]
Yep, sure @ANiknejad : i left some space towards the left to put the parameters. I can use the images you used in the pptx for the first step! :)

**Comment by ANiknejad** [comment]
ok great, Amina, thank you
(and see comments above please)

**Comment by aechchiki** [comment]
Here's an updated version of the pptx, I added the annotation pipeline as in the drawing above, and more details, hope it's good: [draft_biocuration_2016_editAE.pptx](https://github.com/BgeeDB/expression-annotations/files/200310/draft_biocuration_2016_editAE.pptx) 
We can discuss on Monday. 
It could be good is we could add some other boxes after the "final annotation file" (Aspera?Kallisto?), but I need @fbastian advice on that.

**Comment by ANiknejad** [comment]
[draft_biocuration_2016_editANN.pptx](https://github.com/BgeeDB/expression-annotations/files/202258/draft_biocuration_2016_editANN.pptx)

@aechchiki 
@julien-roux

**Comment by ANiknejad** [comment]
another updated version
@aechchiki 
[draft_biocuration_2016_editANN.pptx](https://github.com/BgeeDB/expression-annotations/files/202788/draft_biocuration_2016_editANN.pptx)

thanks a lot, Amina!

**Comment by aechchiki** [comment]
updated version:
[draft_biocuration_2016_editANN_AME.pptx](https://github.com/BgeeDB/expression-annotations/files/204229/draft_biocuration_2016_editANN_AME.pptx)

added: 
- gtex & uberon logos
- detailed stomach example - reformat
- images refs

there's still place for a PCA graph when available

**Comment by ANiknejad** [comment]
@aechchiki 
I like it!

please just change
'from subject with localized disease'
by
'from subject with organ pathology'

I definitely do not like the expression 'local disease'
Many thanks!

@fbastian

**Comment by aechchiki** [comment]
following discussion with @fbastian, here's a new version:

[draft_biocuration_2016_editANN_AME_FB.pptx](https://github.com/BgeeDB/expression-annotations/files/204645/draft_biocuration_2016_editANN_AME_FB.pptx)

- changed the abstract: shorter sentences
- changed the section headers 
- added extract from real annotation file (for pathologist notes)
- changed yes/no/pending for subjects to: healthy/unhealthy/partially healthy
- changed yes/no for samples to: accepted/rejected

Fred said that we are not likely to put a PCA graph, so more space for annotation

let me know what you think about it

**Comment by ANiknejad** [comment]
perfect!
good job indeed! fine with me to go printing
many thanks, Amina, and yes, you will present it easily, it's all your work

**Comment by fbastian** [comment]
@aechchiki: much better version, great! Good rewriting of the intro, and good to see notes from pathologist. 

I think it would be good actually to have a fourth point, "Data re-analysis". Something more technical, like: 

> * Data transfer: use of Aspera software for faster download of large datasets
* Data storage: use of high storage capacity server, hosting all RNA-Seq data used in Bgee, encrypted and in FASTQ format
* Transcript abundance estimation: use of Kallisto software for faster and more accurate estimation of transcript read counts
* TMM normalization, computation of FPKMs and TPMs at gene level
* Generation of calls of presence/absence of expression, and of differential over-/under-expression.

Remarks: 
* Maybe you could display in each box the count corresponding to the step. E.g., in "GTEx subjects", the total number of subjects, in "Healthy" the number of healthy subjects, etc.
* 1) Data filtering: 
  * Actually, I liked how, in the previous version, the samples from "partially healthy" subjects were divided into two arrows, pointing to "accepted" and "rejected". I think it makes the work done much clearer.
  * The yellow writing is unreadable. Maybe you can use colored boxes around highlighted words, as in the figure?
* 2) Data filtering: 
  * "good tissue quality samples" -> "sample quality"?
  * I would remove the "good" and "bad" boxes, they are redundant with regard to the "Accept" and "Reject". Maybe you can say "Accept (good quality)" and "Reject (low quality)"?


Miscellaneous: 
* in the footer, please update Bgee URL to 'http://bgee.org/'
* in the footer, please update SIB URL to 'http://sib.swiss/'
* SIB official affiliation is not 'Swiss Institute of Bioinformatics', but 'SIB Swiss Institute of Bioinformatics'
* The mail address should use the new 'sib.swiss' domain name.
* You could add the Bgee logo to the top right corner, along with UNIL and SIB logos.

I'll be available tomorrow morning for a final look if you want.

**Comment by julien-roux** [comment]
Looks good!
A few details
- "we re-annotated and re-analyzed all GTEx data" -> all RNA-seq data
- yellow writing could be changed to orange (as in traffic lights ;)
- The big red frames/boxes are not the same color as the red title boxes
- In many places: "e.g." -> "e.g.," (US syntax)

Julien

On 4/6/16 1:51 AM, fbastian wrote:
>
> @aechchiki <https://github.com/aechchiki>: much better version, great! 
> Good rewriting of the intro, and good to see notes from pathologist.
>
> I think it would be good actually to have a fourth point, "Data 
> re-analysis". Something more technical, like:
>
>       * Data transfer: use of Aspera software for faster download of
>         large datasets
>       * Data storage: use of high storage capacity server, hosting all
>         RNA-Seq data used in Bgee, encrypted and in FASTQ format
>       * Transcript abundance estimation: use of Kallisto software for
>         faster and more accurate estimation of transcript read counts
>       * TMM normalization, computation of FPKMs and TPMs at gene level
>       * Generation of calls of presence/absence of expression, and of
>         differential over-/under-expression.
>
> Remarks:
>
>   * Maybe you could display in each box the count corresponding to the
>     step. E.g., in "GTEx subjects", the total number of subjects, in
>     "Healthy" the number of healthy subjects, etc.
>   * 1) Data filtering:
>       o Actually, I liked how, in the previous version, the samples
>         from "partially healthy" subjects were divided into two
>         arrows, pointing to "accepted" and "rejected". I think it
>         makes the work done much clearer.
>       o The yellow writing is unreadable. Maybe you can use colored
>         boxes around highlighted words, as in the figure?
>   * 2) Data filtering:
>       o "good tissue quality samples" -> "sample quality"?
>       o I would remove the "good" and "bad" boxes, they are redundant
>         with regard to the "Accept" and "Reject". Maybe you can say
>         "Accept (good quality)" and "Reject (low quality)"?
>
> Miscellaneous:
>
>   * in the footer, please update Bgee URL to 'http://bgee.org/'
>   * in the footer, please update SIB URL to 'http://sib.swiss/'
>   * SIB official affiliation is not 'Swiss Institute of
>     Bioinformatics', but 'SIB Swiss Institute of Bioinformatics'
>   * The mail address should use the new 'sib.swiss' domain name.
>   * You could add the Bgee logo to the top right corner, along with
>     UNIL and SIB logos.
>
> I'll be available tomorrow morning for a final look if you want.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/BgeeDB/expression-annotations/issues/127#issuecomment-206039228>
>

-- 
Julien Roux
Department of Ecology and Evolution, University of Lausanne, Switzerland
http://www.unil.ch/dee/home/menuinst/people/post-docs--associates/dr-julien-roux.html
Tel: +41 78 700 2931
Twitter: @_julien_roux

**Comment by ANiknejad** [comment]
@fbastian 
well spotted remarks...sorry missing at least mail and URL changes  :-(

**Comment by aechchiki** [comment]
thanks @fbastian and @julien-roux for the comments

here's an new version, let me know what you think about it. asap, so that I can send it to the repro (yay! :3)
[draft_biocuration_2016_editANN_AME_FB.pptx](https://github.com/BgeeDB/expression-annotations/files/206562/draft_biocuration_2016_editANN_AME_FB.pptx)

**Comment by julien-roux** [comment]
Looks good !
Very small details:
" e.g., brain sample from ascites subject " is not left aligned at the 
same position as bullet points below
" e.g.,     - GTEx 'stomach' target, preferred location 'body'": I would 
put bullet points instead of "-" as in rest of poster
"4859 RNAseq samples
78 anatomical structures": left alignement is a bit strange, I would 
move it the the right to move it below "Final Bgee annotation file "

On 4/6/16 4:10 PM, Amina Echchiki wrote:
>
> thanks @fbastian <https://github.com/fbastian> and @julien-roux 
> <https://github.com/julien-roux> for the comments
>
> here's an new version, let me know what you think about it. asap, so 
> that I can send it to the repro (yay! :3)
> draft_biocuration_2016_editANN_AME_FB.pptx 
> <https://github.com/BgeeDB/expression-annotations/files/206562/draft_biocuration_2016_editANN_AME_FB.pptx>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/BgeeDB/expression-annotations/issues/127#issuecomment-206389925>
>

-- 
Julien Roux
Department of Ecology and Evolution, University of Lausanne, Switzerland
http://www.unil.ch/dee/home/menuinst/people/post-docs--associates/dr-julien-roux.html
Tel: +41 78 700 2931
Twitter: @_julien_roux

**Comment by aechchiki** [comment]
thanks @julien-roux :)

here's a new version: 
[draft_biocuration_2016_editANN_AME_FB.pptx](https://github.com/BgeeDB/expression-annotations/files/206623/draft_biocuration_2016_editANN_AME_FB.pptx)

**Comment by fbastian** [comment]
Another very small detail, maybe the Bgee logo used should be the one with "gene expression evolution" below. But I really don't mind :p

Great job!

**Comment by aechchiki** [comment]
Voilà, logo updated (and aligned the footer 'http://sib.swiss/' to the square section width ;) )

[draft_biocuration_2016_editANN_AME_FB.pdf](https://github.com/BgeeDB/expression-annotations/files/206743/draft_biocuration_2016_editANN_AME_FB.pdf)
[draft_biocuration_2016_editANN_AME_FB.pptx](https://github.com/BgeeDB/expression-annotations/files/206742/draft_biocuration_2016_editANN_AME_FB.pptx)

So can I send it for print? :)

**Comment by fbastian** [comment]
Yep, looks great!

**Comment by aechchiki** [comment]
okay :) thanks
