### ISSUE TITLE
GSE53690

### ISSUE THREAD

**Issue by ANiknejad** [BgeeDB/expression-annotations#14]
to replace 
MmulDv:0000021 	mature stage
by
UBERON:0000113
name: post-juvenile adult stage

This is what we use for general 'adult' stage. Information from the paper is also 'adult'.

NB: In GSE43013 there is another annotation with 
UBERON:0018241 	prime adult stage
while information is 'adult' from the GEO interface, but in the paper we found:
'terrestrial mammals of young adult age', so this is 'prime adult stage'.
(Was my job, I had to precise that in 'comments')

**Comment by aechchiki** [comment]
done. 

commit hash : 1ef6342fbca3eee94028044c7df7080400673b27

**Comment by ANiknejad** [comment]
Thank you!
