### ISSUE TITLE
GEO GSE30352, RNA seq technical replicates not clear and clarification on 'replicates' in Bgee

### ISSUE THREAD

**Issue by ANiknejad** [BgeeDB/expression-annotations#2]
http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE30352

Technical replicates are claimed in GEO interface and the paper
http://www.ncbi.nlm.nih.gov/pubmed/22012392

'Technical replicates (i.e., sequencing the same library on different machines) were performed to rule out potential biases during the sequencing step'

However not clear to track these replicates.
For examples:

GSM752615 	mmu br M 1
GSM752616 	mmu br M 2

 GSM752615 	
sample name: B6_br
C57BL/6 mouse; library generated from pool of brain RNAs extracted from 3 mice

GSM752616 	
sample name: 670
Wild type mouse

**Comment by ANiknejad** [comment]
2011-03-04037D-Brawand_etal_Supp_Tables1-2.xls
all information there

**Comment by ANiknejad** [comment]
I would like to clarify things, please help 
@julien-roux 
@fbastian 

If we annotate following our rules of annotation in Bgee pipeline (only Organ and Stage)
organ brain
stage adult

twice, one from male, on from female (because we report sex but this is not taken in account currently in the pipeline) do we need to tag as biological replicates? they obviously select a different organism to investigate (so not replicates), but FOR US, organ and stage look as replicates

**Comment by julien-roux** [comment]
I would say that this is fine: we do not take sex into account for now, so we consider these as biological replicates. If later we take sex into account they would be different conditions

**Comment by fbastian** [comment]
Yep, same opinion.

**Comment by ANiknejad** [comment]
Thank you for explanation!
Yes, we have to track 'technical replicates' mainly because 'biological replicates' are depending on the granularity of our annotation.

**Comment by ANiknejad** [comment]
again...we have in the same experience:
UBERON:0002107	liver	UBERON:0018241	prime adult stage	whole liver	F Bos taurus	1
UBERON:0002107	liver	UBERON:0018241	prime adult stage	whole liver	M Bos taurus	2
UBERON:0002107	liver	UBERON:0018241	prime adult stage	whole liver	F dog	1
UBERON:0002107	liver	UBERON:0018241	prime adult stage	whole liver	M dog	2

and the annotator correctly tagged the biological replicates...BUT won't the pipeline at the end consider 2 group of technical replicates??? (1 1) and (2 2) ???

@fbastian

**Comment by ANiknejad** [comment]
in such case better to not annotate the biological replicates inside each taxon?

**Comment by julien-roux** [comment]
These are from different species, so they cannot be biological replicates 
Or did I miss something?

**Comment by ANiknejad** [comment]
Sure, they are not, and yes, our pipeline consider the TaxonID!! We are saved!!
Sorry, was a silly question, but this is because we (annotator) report a lot of columns (e.g sex) not taken into account currently, and I had a terrible fear ;-)
