### ISSUE TITLE
RNASeqLibrary.tsv, columns and format

### ISSUE THREAD

**Issue by ANiknejad** [BgeeDB/expression-annotations#41]
please check,
there are info replicate in column 'comments'
example
GSM694285 	GSE44612

**Comment by ANiknejad** [comment]
please check all column TaxID because sounds like many taxon are reported with a space in front of them?

**Comment by ANiknejad** [comment]
please check UberonID column, sounds like there are still UBERON_  ?

**Comment by aechchiki** [comment]
taxID column cleaned from unwanted spaces; commit hash: 2a8a784ddea0911d549f0648013258b34e4d9412 
ontologyID fomat fixed; commit hash: cab90e2ab1e083b2aef91e6740614b162a1383bb

**Comment by ANiknejad** [comment]
Caution: sounds like the TaxID has not the correct format!

https://raw.githubusercontent.com/BgeeDB/expression-annotations/2a8a784ddea0911d549f0648013258b34e4d9412/annotations/rna_seq/RNASeqLibrary.tsv

all TaxID look like
9606

while they should be
"9606"

Could you manage to check and correct that please? Maybe problem at time you remove the additional space?
many thanks

**Comment by fbastian** [comment]
You don't need quotes when a column contains numbers only, it's fine.

**Comment by aechchiki** [comment]
Very good. 
(but is there a reason why that field is not quoted?)

**Comment by fbastian** [comment]
With the export I showed you, it only quotes text field, which is fine.

**Comment by ANiknejad** [comment]
Thank you, Fred, for explanations!
