### ISSUE TITLE
GTEx restricted access dataset

### ISSUE THREAD

**Issue by fbastian** [BgeeDB/expression-annotations#44]
See the wiki for a description of the files available: https://github.com/BgeeDB/expression-annotations/wiki/GTEx-data-annotation

* First task is to carefully look at each column of the relevant files ;) @ANiknejad, do you agree to take care of this "column review"?

* What should we do for samples from non-tumor tissues, taken from a subject with tumor?

* Not clear to me whether we could use directly the file SraRunTable_SRA_data.txt for annotations, rather than using the "data tables" available (see wiki). I think we have more information in the data tables, so it should be better. 

* If we use the data tables, then the first step is to annotate the subjects. We could then discard the samples from "non-normal" subjects. 

* SRA IDs: not clear to me whether we should use SRR IDs or SRS IDs. (see for instance file SraRunTable_SRA_data.txt). @smoretti, @julien-roux, do you have any idea?

* Not clear to me whether we should use the GTEx_submitted_ID, the gap_sample_id, or the SRA sample IDs for our sample annotations.

* Rough mapping of tissues provided by the GTEx consortium: http://thinklab.com/discussion/processing-gtex-for-tissue-specific-gene-expression/82#306

**Comment by julien-roux** [comment]
> What should we do for samples from non-tumor tissues, taken from a subject with tumor?

My 2 cents: as there are so many individuals in GTEx, I would drop all tissues from a subject with tumor

> SRA IDs: not clear to me whether we should use SRR IDs or SRS IDs. (see for instance file SraRunTable_SRA_data.txt). @smoretti, @julien-roux, do you have any idea?

Where to you access the SraRunTable_SRA_data.txt (sorry)?
According to the NCBI (http://www.ncbi.nlm.nih.gov/books/NBK56913/), SRR IDs are for sequencing runs of an experiment and SRS for samples. So there should be several SRS IDs for one SRR ID.

**Comment by fbastian** [comment]
@julien-roux the folder has been shared with you (check you SIB mail maybe). 

You mean, several SRR IDs for one SRS ID, don't you?

**Comment by julien-roux** [comment]
Yes, you're right, I was thinking that 1 run = 1 flow cell (with many samples), but actually 1 run (SRR) seems to be 1 technical replicate of a sample (SRS) in a given experiment (SRX) in a given project (SRP).
So far you used SRP and SRX IDs?

**Comment by ANiknejad** [comment]
Yes, this is what we annotators do, SRP is reported in the 'Experiment ID' column and each corresponding SRX in the '#ChipID' column of the standard expression data annotation file

(so SRX like 'GSM' and SRP like 'GSE' from Affymetrix)

**Comment by ANiknejad** [comment]
phs000424.v5.pht002742.v5.p1.c1.GTEx_Subject_Phenotypes.GRU.txt

not sure to understand how the column INCEXC has to be considered: this is the column 'Eligible For Study' but even FALSE subject are reported in phs000424.v5.pht002743.v5.p1.c1.GTEx_Sample_Attributes.GRU.txt

Donor Eligible A verification field of whether the Donor has met the overall eligibility criteria for GTEx collection based on answers to eligibility questions. All Eligibility conditions require confirmation from the donor procurement team (staff team where tissue collection and data abstraction takes place) and must be met in order for donor to eligible.

**Comment by fbastian** [comment]
@ANiknejad, @julien-roux seems to say that it would be SRS the equivalent of GSM, not SRX.

For the INCEXC, I see from the 'var_report.xml' that there are only 10 subjects with a value of FALSE, so let's just discard them. It's OK, we anyway already planned to first filter the subjects before annotating the samples.

**Comment by fbastian** [comment]
SRX is indeed what we need, it is the ID of the library. SRS is the ID of the sample, but I guess the sample could be used for many other things (like in GTEx data, a same sample used to study histone modification, expression, etc).

**Comment by fbastian** [comment]
Hmm, problem is, the GTEx file provides the SRS IDs, not the SRX, grrrr...

**Comment by julien-roux** [comment]
You're right Fred.
Apparently for GTEx, one SRS ID corresponds to one SRX ID and to one SRR ID.
But there can be multiple SRR IDs for one SRX ID. I guess this corresponds to technical replicates (additional reads were sequenced from the same library from a new sequencing run)

BTW, I see that for previous RNA-seq experiments you used SRX IDs to name the data files, shouldn't you use SRR IDs?

**Comment by fbastian** [comment]
@julien-roux: no, we annotate SRX IDs, and then just pull automatically the related SRR IDs. There shouldn't be anything special to annotate about runs (but in the database, we store info about runs included/discarded).

**Comment by ANiknejad** [comment]
we decided today to report SRX instead of GSM for still GSE experiments
