### ISSUE TITLE
GTEx normality check in phs000424.v5.pht002742.v5.p1.c1.GTEx_Subject_Phenotypes.GRU.txt

### ISSUE THREAD

**Issue by ANiknejad** [BgeeDB/expression-annotations#45]
For cause of death: cf column DTHFUCOD First Underlying Cause Of Death
irst underlying Cause of Death A disease or injury, leading to the cause of death listed in immediate_cause_of_death.

The inconsistency in reporting information (ex:'probable MI' and 'probable myocardial infarction' and 'possible myocardial infarction') generates more than 200 death reasons...
Some of them are easy to remove regarding 'normality' (ex: all 'toxic' one) but others are less clear,
so help welcome.
I propose to select at least 'trauma', 'suicide by hanging', 'GSW' (gun shot wound) as fine for normal conditions. 

aaa
abdominal aortic aneurysm secondary to arterial thrombosis left lower extremity
accident unspecified
Acute Cerebellar infarct with obstructive hydrocephalus
acute cocaine intoxication
acute mi
Acute myocardial infarction
acute renal failure
acute renal failure secondary to polycystic kidney disease
Acute Respiratory Distress Syndrome
alcohol abuse
alcoholic cirrhosis of liver
allergic reaction
als
anoxia
anoxia secondary to hanging
anoxic brain injury
anoxic brain injury secondary to cardiac arrest
Anoxic encephalopathy
arrest [as an cardiac arrest]
arrest; cardiac
asphyxia secondary to hanging
Asphyxiation
aspiration
aspiration pneumonia due to regurgitated food
assault by other and unspecified firearm and gun discharge
Asyphyxiation
asystole
atherosclerotic cardiovascular disease
Atrial fibrillation
Blunt force trauma
blunt force trauma to head
Blunt Injury
bowel obstruction
breathing arrested
breathing difficult
cad
Cardiac arrest
cardiac arrest, unspecified
cardiac asystole
Cardio-Pulmonary Arrest
Cardiovascular
cardiovascular collapse
cardiovascular disease other
cardiovascular; collapse
Cardivascular
cause unknown; death
Cerebral Vascular Accident
Cerebral Vascular Accident (Intracranial hemorrhage)
Cerebral vascular accident secondary to anti-coagulation
cerebrovascular dis
cerebrovascular disease
change in mental status
chest pain
CHF
CHF exacerbation
complications from ALS
contact with blunt object, undetermined intent, sequela
COPD
COPD/pulmonary edema
CPA
CVA
cva - cerebrovascular accident
CVA traumatic brain injury
dehydration
Diabetic Emergency
dissection aortic
Drug Intoxication
DTHFUCOD
Dysphagia with recurrent aspiration
electrolyte imbalance
embolism pulm
empyema, lung
end stage COPD
end stage liver disease
end-stage renal disease
end-stage renal failure
epilepsy
ESLD
ESRD
EtOH abuse
gi - gastrointestinal bleed
gi bleed
GSW
GSW to back
gun shot wound
gunshot wound
Gunshot Wound to Head
Hanging
head injury
Head trauma secondary to MVA
Heart Attack/Stroke
Heart disease
heart disease (MI)
Heart failure
hepatic encephalopathy
hepatitis acute
Hepatorenal Syndrome
hypertension
hypoxemia
ICH
infarcted bowel secondary to AAA repair
injury
injury from an external force
injury of head
intent self harm by hanging strangulation / suffocation
Intercranial Hemmorage
Intracranial hemmorhage
Intracranial hemmorhage secondary to Arteriovenous malformation
Intracranial Hemorrhage
intracranial hemorrhages
intracranial; hemorrhage
intraperitoneal bleed
ischemic cardiomyopathy
Kidney diseases
kidney failure
lactic acidosis
Liver disease, alcoholic
liver failure
Liver Transplant
lung cancer
Metabolic acidosis related to diabetic ketoacidosis
MI
mi - myocardial infarction
mi, myocardial infarction
motor vehicle accident
Motor vehicle accident trauma
motorcycle accident
motor-vehicle accident [mva] nos
MSOF secondary to NSTEMI
multiple blunt force trauma
multiple blunt force trauma secondary to motor vehicle accident
multiple blunt force trauma secondary to MVA
mva - motor vehicle accident
MVA Trauma
myocardial infarction
N/A
NA
natural causes
NONE
non-ischemic cardiomyopathy
non-ST elevation myocardial infarction
NSTEMI
NSTEMI with anoxic brain injury due to prolonged CPA
pe
pe - pulmonary embolism
phv00169091.v5.p1.c1
Pneumonia
pneumothorax
Pontine Bleed
possible myocardial infarction
posterior wall myocardial infarction
prescription drug overdose
probable  myocardial infarction
probable drug overdose
probable MI
probable myocardial infarction
probable overdose
pulmonary arrest
pulmonary disease
pulmonary embolism
Renal failure
Resp-Asphyxiation
respiration; arrest
respiratory arrest
respiratory difficulty
Respiratory disease
s/p Hanging
sah
SAH and intraventricular hemorrhage secondary to head injury
Seizure
seizure disorder
seizures
Self Inflicted GSW to head
sepsis
Shock secondary to burns
shortness of breath (sob)
SIGSW
sinus [sinusal] tachycardia nos
smoke asphyxiation
smoke inhalation-respiratory disease
Stroke
Subarachnoid hemorrhage
subdural hematoma secondary to fall
subdural hemorrhage following injury
suicide by hanging
suicide-hanging
suspected overdose
thrombocytopenia
tia
toxic effect of unspecified substance
trauma
trauma due to fall
trauma SAH/SDH
trauma, head
trauma;multiple
Trauma-blunt force trauma secondary to MVA
trauma-head bleed result of a fall
traumatic brain injury
unknown
unknown cause of death
vascular cerebral accident

**Comment by ANiknejad** [comment]
@fbastian 
@julien-roux

**Comment by fbastian** [comment]
I'm not sure that drug intoxications/overdoses have such a big effect on gene expression. 

I think I would not put too much constraints on the cause of death, I don't think we need to discard all diseases. What about the other columns? There might be information easier to use (like a clearly bad BMI).

**Comment by marcrr** [comment]
I think that drug intoxications/overdoses are not "normal" and should be excluded.
It would be helpful to have a list of borderline cases for discussion. For example "vascular cerebral accident" might count as normal?

**Comment by fbastian** [comment]
Also, it would be nice to know how many subjects are in the different categories intoxication/cancer/accidents/hard to decide.

**Comment by ANiknejad** [comment]
@aechchiki 
@mimiblis 

please have a look at that file, having already added information on some columns, list below.
Columns of interest, or at least to check first, are, I guess:

D
E
F
L
M
N
T
U
AA
AH
AI
AJ
AZ
BA
BB

BD and further: serology

[phs000424.v5.pht002742.v5.p1.c1.GTEx_Subject_Phenotypes_ANN.GRU.txt](https://github.com/BgeeDB/expression-annotations/files/3552/phs000424.v5.pht002742.v5.p1.c1.GTEx_Subject_Phenotypes_ANN.GRU.txt)

**Comment by ANiknejad** [comment]
Regarding serology, please check 

column BM for HIV virus
nameLBHIV1NT

and remove valeur = 1

**Comment by ANiknejad** [comment]
Remark:
depending on the sorting and selection you do, there is no more HIV positive to remove after removing by (step by step)
1) BMI
2) eligibility
3) DTHHRDY

**Comment by ANiknejad** [comment]
Caution: 
diseases information reported into column BR and further (BS, BT, ...) are 'not used to determine eligibility', so please check carefully!

**Comment by mimiblis** [comment]
how should we understand "presumed death"?
and BTW @ANiknejad you said BMI up to 29.99 right?

**Comment by aechchiki** [comment]
@mimiblis: apparently, "actual death" of an individual can only be stated by a qualified doctor, while "presumed death" of an individual can also be stated by anybody else (other than the qualified doctor). 

Source: https://en.wikipedia.org/wiki/Legal_death

**Comment by mimiblis** [comment]
Thanks à lot. This is quite "funny" morbidly spoken :-$

**Comment by fbastian** [comment]
Haha, good catch @aechchiki, this is indeed quite interesting :p

**Comment by mimiblis** [comment]
For me lots of BMI>29.99, so lots of eliminated poeple... some of them even gave their organs as donor, maybe we have to discuss that?

**Comment by aechchiki** [comment]
@mimiblis , I also discarded ~70 individuals according to BMI out of range...  btw, I guess that being overweight is not a criterion to be excluded from organ donation, in fact "There is no binding donor weight limit, but a little more than half of transplant centers cap donor body mass index at 35" (Source: http://well.blogs.nytimes.com/2012/08/06/transplant-centers-struggle-with-donors-obesity/?_r=0 ). 
In our dataset, I also observed that individuals who died because of drug intoxication could donate his organs, so.... lol :P

**Comment by mimiblis** [comment]
damn, you may recieve a fatty heart... haha. but still loads of individuals, so maybe we should not be so astrangeant... to see with Anne and Fred

**Comment by ANiknejad** [comment]
http://www.ncbi.nlm.nih.gov/pubmed/24507024

then sounds ok to consider BMI up to 35 for organ donation, so yes, we can maybe include them (if they are TRUE as well)

**Comment by ANiknejad** [comment]
https://en.wikipedia.org/wiki/Body_mass_index
Obese Class I (Moderately obese) 	from 30 to 35

let's consider this status as a normal one...(at least for USA...)

**Comment by marcrr** [comment]
I agree with considering BMI up to 35 normal, at least for now.
