### ISSUE TITLE
RNA-seq replicates

### ISSUE THREAD

**Issue by ANiknejad** [BgeeDB/expression-annotations#48]
RNASeqLibrary.tsv

Please (re-) do review of all the file and tag mine (ANN)

Many thanks, Amina

**Comment by aechchiki** [comment]
- GSE30352
https://github.com/BgeeDB/expression-annotations/commit/b7cf85f64d0839f00a5961a01d3f395e5212693e (info replicates on GEO)

**Comment by ANiknejad** [comment]
GSE30352
please correct the replicate tag for GSM752642 and GSM752643: they are not replicates (not the same age)

**Comment by aechchiki** [comment]
Done. 60c013528dfba1ef0cd01f08aa5bc45a896b47eb (sorry)

**Comment by ANiknejad** [comment]
GSE43520
there are replicates not yet tagged.
example
GSM1064854 and GSM1196055
are biological replicates ( so 1 and 2)

also
GSM1064848
GSM1196051
GSM1196052
3 biological replicates
to annotate as replicates because here placenta are reported on the adult sexually mature stage, so this is typically a case of biological replicates due to the granularity of our annotations

same with GSM1064828
it is also a biological replicate as 
GSM1196043 and GSM1196044
already are

Caution:
GSM1064843
GSM1064844
and
GSM1196048
GSM1196049
have to be all together annotated as biological replicates 1  2  3  4
Such as you did currently, GSM1064843
and GSM1064848 would be seen as technical replicates (both have same organ and stage and same tag = 1)
(Again this problem is due to our way of annotating on the mature stage)

**Comment by ANiknejad** [comment]
still GSE43520 (sorry, please tell me if something is not clear or if I am wrong too;-)  )
GSM1064851
GSM1196053
GSM1196054
are 3 biological replicates

GSM1064864
GSM1196057
biological replicates

GSM1064865
GSM1196056
biological replicates

**Comment by ANiknejad** [comment]
GSE43013
here something interesting, I guess: the same stage is allocated to same organs from different taxons. So far I understand, it artificially creates 'technical replicates' between taxons, to check with Fred, see #2

**Comment by ANiknejad** [comment]
Forgot previous comment, TaxID is taken into account by the pipeline and makes the difference....

**Comment by ANiknejad** [comment]
GSE43013
is ok, well tagged

Waiting for corrections on GSE43520, see above

**Comment by fbastian** [comment]
@smoretti: could you please double-check that tax ID is taken into account when producing groups of samples for diff expression analyses?

**Comment by aechchiki** [comment]
Replicates tag updated: 9ebd8f739505d5d3cd8ace870d896d6d728942a1

**Comment by ANiknejad** [comment]
done

**Comment by fbastian** [comment]
Actually, no :p we haven't heard back from @smoretti about tax ID being correctly taken into account (see question above)

**Comment by ANiknejad** [comment]
I remember, he said 'yes' during a meeting...

**Comment by fbastian** [comment]
Haha, sorry.
