### ISSUE TITLE
GSE41338: replicate tagging note

### ISSUE THREAD

**Issue by aechchiki** [BgeeDB/expression-annotations#50]
In the section "material and methods" of the related paper, the authors described the samples, saying that "RNA  samples  analyzed  by  RNA-Seq comprised pools of at least two females and two males from each species". 
Subsequently, I guess that samples GSM1015150 and GSM1015151 (both of them are "mouse brain"), tagged in GEO as rep1 and rep2, are technical replicates. Not sure about it, though. 

commit hash: 74a92e5db2c33f252273d622612c0fd1db5adef9

**Comment by fbastian** [comment]
Well, do you have the information that samples GSM1015150 and GSM1015151 comes from the same individuals? Maybe we have: 

GSM1015150 = Male1 + Male2 + Female1 + Female2 and GSM1015151 = Male3 + Male4 + Female3 + Female4 
=> biological replicates

Do you know the number of individuals used in total?

**Comment by ANiknejad** [comment]
I guess, you are right, Fred. In Suppl file they talk about 'standard error of the mean across biological replicates' (nowhere mention of 'technical replicates'), and also they talk about 'comparing samples from different individual within the same species'

**Comment by aechchiki** [comment]
Done: 0901bd0fd8c66401f09b67da4730a14224d62ab0

**Comment by ANiknejad** [comment]
Thank you, Aminan.
Could you just replace
UBERON:0000113	adult frog stage

by

UBERON:0000113 post-juvenile adult stage

Many thanks in advance

**Comment by aechchiki** [comment]
Done :) fdae2507c4c5ce1ff63489fd2b62d3b9404fb9a6

**Comment by ANiknejad** [comment]
Many thanks!
