### ISSUE TITLE
GSE58387 and GSE58608: replicate tagging note

### ISSUE THREAD

**Issue by aechchiki** [BgeeDB/expression-annotations#52]
The authors took samples from skeletal muscle of right and left leg of each individual who participated in the study (with one exception). Since Uberon makes no difference between right/left leg, all the samples from one individual have exactly the same annotation features. 
Thus, I tagged all replicates from one individual with the same number (as if they were "technical" replicates). I hope this is the right way to do it :)

**Comment by julien-roux** [comment]
I think these should be considered biological replicates.
To me this is analogous to growing the same cell culture twice independently
(Biological replicates do not have to be from different individuals / genotypes)
@fbastian Do you agree?

**Comment by fbastian** [comment]
Yep, I see the same confusion in another issue, @aechchiki, we should discuss this rapidly.

**Comment by ANiknejad** [comment]
Amina, please refer to explanation about replicates in #2 

if the sample is re-done from the vivo, this is a biological replicate (and this is the default condition in Bgee: we group biological replicates to generates diff. expression) BUT we have to track 'technical replicate' when the same sample is reused to generate new data.

**Comment by ANiknejad** [comment]
i will update the wiki about replicates

**Comment by aechchiki** [comment]
Done: tagged as biological replicates.
GSE58387: 1523c9a8cd325e513ad7fc107a2abe40cfcd8f10 
GSE58608:  2c21b8a2add593c7cab0a61dc3aec988c97d8e54

**Comment by ANiknejad** [comment]
great, many thanks!
