### ISSUE TITLE
GTEx normality - Serology information 

### ISSUE THREAD

**Issue by aechchiki** [BgeeDB/expression-annotations#54]
This is an issue regarding columns about virus/parasite Serology: 

1. col.BD: herpesviridae, subfamily betaherpesvirinae.  They can establish latency in leukocytes, or undergo nuclear lysogenic viral replication.  Human tissues which can be affected: T-cells, B-cells, NK-cell, monocytes, macrophages, epithelial. (Source: https://en.wikipedia.org/wiki/Betaherpesvirinae) >>> Should we conditionally discard positive individuals (if one of the potentially affected  tissues was sampled)?

2. col.BE, BF:  Epstein–Barr virus (EBV). Most people become infected with EBV and gain adaptive immunity, but can also be cause of mononucleosis, and a risk factor for cancer or autoimmune diseases (https://en.wikipedia.org/wiki/Epstein%E2%80%93Barr_virus) >>> Should we accept positive individuals (knowing that ~90% of human population is chronically infected)?

3. col. BG, BH, BI, BJ: Hepatitis B virus. Such a virus is known to specifically infect liver cells (or increase the chances to develop a pancreatic cancer).  (Source: https://en.wikipedia.org/wiki/Hepatitis_B_virus) >>>  Should we conditionally discard positive individuals (if one of the potentially affected  tissues was sampled)?

4. col. BK, BL: Flaviviridae. Such a virus family is known to cause acute and severe diseases (hepaciviruses: hepatitis; pestiviruses: hemorrhagic syndromes, abortion, fatal mucosal disease; flavivirus: hemorrhagic fever, encephalitis), and can replicate in all kind of epithelium. (Source: https://en.wikipedia.org/wiki/Flaviviridae ) >>> I think we should discard all positive individuals (?)

5.  col. BM, BN, BO : HIV >> We discussed that all positive individuals should be discarded, right?

6. col. BP, BQ : syphilis (or siphilis agent, T.pallidum) >> I think we should discard all positive individuals (?)

Also, how are we supposed to proceed when the individuals have a serology status other than 0 or 1 (not tested, for example)? Should we act in a pessimistic way, to minimize "potentially infected" subjects, or not?

**Comment by mimiblis** [comment]
- lots of 'not tested'
- lots of POS have given organs, so I think that most of these 'latency' virus (beside HIV) should be accepted. otherwise lots of individuals discarded

**Comment by fbastian** [comment]
Add HIV serology column, we'll see later if we keep the "not tested"
