### ISSUE TITLE
GTEx normality - Causes of death 

### ISSUE THREAD

**Issue by aechchiki** [BgeeDB/expression-annotations#56]
Explanation for status in annotation file (AME tag): 
(hash: fc14a7ac5f1b4ada9243b488b1402794c36bd44d)

1. status "NO" for death due to: 
    - drug abuse/intoxication/overdose
    - Hardy Scale 3-4
    -  (other parameters): bmi> 29.99 and/or HIV positive)

2. status "PENDING" for death due to:
    - wound/bullet (head) >> discard head tissue from  from analysis?
    - (other parameters): herpesvirus positive
    - known "heart disease" >> discard heart tissue from from analysis? but take other organs?
    - end stage disease (end-stage renal/ liver disease)... not sure

3. status "YES" for death due to: 
    - cardiovascular accident/ cardiac arrest/ cardiac failure - not due to illness; 
    - stroke/ seizure - not due to illness;
    - suicide by hanging; 
   - motor vehicle traumatic accident; 
    - blunt shock (no wounds/bullets involved) / hemorrages - not due to illness; 
   - smoke inhalation

**Comment by mimiblis** [comment]
We will have to discuss this tomorrow because by Doubt I have put most "pending" to  the causes you annotated as "yes" ;-) because of the organes that May be touched or not (#55). So that we have at the end one and unique "kind of classification"

**Comment by fbastian** [comment]
See issues#55.
