### ISSUE TITLE
GTEx anatomical structure mapping (phs000424.v6.pht002743.v6.p1.c1.GTEx_Sample_Attributes.GRU.txt)

### ISSUE THREAD

**Issue by ANiknejad** [BgeeDB/expression-annotations#57]
good news!

phs000424.v5.pht002743.v5.p1.c1.GTEx_Sample_Attributes.GRU.txt

the mapping is already done by the LDACC = Laboratory, Data Analysis, and Coordinating Center of the GTEx project
https://commonfund.nih.gov/GTEx/index

see columns 
SMUBRID  Uberon ID, anatomical location as described by the Uber Anatomy Ontology (UBERON)
and
SMUBRTRM  Uberon Term, anatomical location as described by the Uber Anatomy Ontology (UBERON)

SMUBRID the Uberon ID is truncated: '2190' means UBERON:0002190

---> any automatic way to retrieve the correct UBERON id?

**Comment by ANiknejad** [comment]
maybe we have to be confident on this mapping 'Generated at LDACC' because sometimes the mapping is more precise than the available information (ex information 'lung' mapped on UBERON:0008952
name: upper lobe of left lung)

**Comment by ANiknejad** [comment]
at contrario, here an example where information sounds not to be fully retrieved

Brain - Cerebellar Hemisphere	  mapped on UBERON:0002037
name: cerebellum

while an precise Uberon term exists: 
UBERON:0002245
name: cerebellar hemisphere

**Comment by ANiknejad** [comment]
SMSTYP
Indicates whether sample is a tumor or a normal

**Comment by ANiknejad** [comment]
SMPTHNTS
Pathology Notes, notes from PRC Report
Comments from pathological review Any comments the pathologist filling out the PRC form wishes to make concerning the tissue quality.

**Comment by ANiknejad** [comment]
I am a bit confused....SMPTHNTS sounds like having (sometimes) interesting information that are not taken into account in further annotations.
Example for the same sample:
SMPTHNTS  = 1 piece 5x5 mm anterior pituitary
SMSMPSTE Tissue Location The location on the organ or tissue from which the specimen was collected.  = entire
SMTS Tissue Type, area from which the tissue sample was taken. This is a parent value to SMTSD. =pituitary
SMTSD Tissue Type, more specific detail of tissue type = pituitary

'anterior pituitary' is UBERON:0002196 adenohypophysis

**Comment by ANiknejad** [comment]
I decided to consider SMPTHNTS and to report extra-information to map on Uberon

**Comment by ANiknejad** [comment]
Depending on the mapping with conserved subjects, some samples (organs) can be selected depending on column SMPTHNTS (patholoy notes), see below difference between these 2 samples:

1268260	GTEX-11ZTT-0426-SM-5EQLK Artery-coronary 2 pieces, calcific atherosclerosis 
1272273	GTEX-Y5V6-0326-SM-4VBRW Artery-coronary 2 pieces, 2x2 & 3x2.5mm; no significant plaques

**Comment by ANiknejad** [comment]
860692	GTEX-RVPV-0226-SM-2TF6W
860693	GTEX-RVPV-0226-SM-2XU9L

wrongly annotated?
radial artery reported as Artery-tibial

**Comment by ANiknejad** [comment]
Cerebral frontal pole -right

is annotated in 2 different ways: 
cerebellum
frontal cortex

examples
1664094	GTEX-TSE9-2926-SM-5CHQO_rep1
1267927	GTEX-11OC5-0626-SM-5HL6M

**Comment by ANiknejad** [comment]
For Brain region:
presence of Purkinje cell, def. The output neuron of the cerebellar cortex

**Comment by ANiknejad** [comment]
1108854	GTEX-PWO3-1526-SM-48TCM
erroneous annotation, abdomen mapped on skin of leg

**Comment by ANiknejad** [comment]
another error, discrepancy between columns SMPTHNTS (Pathology Notes) and SMSMPSTE (Tissue Location)

1269900	GTEX-13NYB-3226-SM-5J2ND	1	Aqua Kit: Organ and Tissue Donation	B1	Tissue:PAXgene Preserved		Tissue:Fresh Tissue	 
SMPTHNTS  2 pieces, cerebellum, no abnormalities	7.1	
SMSMPSTE    Entire pituitary gland

GTEx annotation is done on cerebellum....

**Comment by ANiknejad** [comment]
good example of discrepancy of reporting information: 

1271901	GTEX-WRHK-1126-SM-4MVOJ

in column SMPTHNTS (Pathology Notes), we found these comment:
'6 pieces, up to 9x3mm; mainly muscle (our target) but 3 have foci of mucosa at one pole'
and annotation is made on 
UBERON:0001159 sigmoid colon
and I let the annotation as is
BUT other sigmoid colon samples with comment '6 pieces, up to 7x3mm; all muscularis, good specimens' will be annotated on the new Uberon term 
UBERON:0035805 muscle layer of sigmoid colon
(https://github.com/obophenotype/uberon/issues/1162)

**Comment by ANiknejad** [comment]
information 'target' in column SMPTHNTS is available for only 78 lines in the table, while it is a very useful information to understand the sample

**Comment by ANiknejad** [comment]
'Muscularis of  lowest portion of esophagus'
is annotated by GTEx on 
UBERON:0004550
name: gastroesophageal sphincter

I consider that wrong, it should be on 
UBERON:0011878	muscle layer of esophagus

Any thoughts from GTEx?
@fbastian

**Comment by ANiknejad** [comment]
For tissues of gastrointestinal tract, please consider these two misleading structures: 
the 'muscularis propria' = muscularis externa = muscularis layer
AND
the 'muscularis mucosa', part of the muscosa
http://www.histology.leeds.ac.uk/digestive/GI_layers.php

**Comment by fbastian** [comment]
OK, it seems clear that we should contact directly the GTEx consortium to investigate. This is a lot of information here :p I'll try to pick up some good examples from your list, but please don't hesitate to let me know if you like some more ;)

**Comment by fbastian** [comment]
BTW, are you working on the version 6? In that case we should update the issue title.

**Comment by ANiknejad** [comment]
yes, thanks, done
