### ISSUE TITLE
GTEx normality - individual cases

### ISSUE THREAD

**Issue by aechchiki** [BgeeDB/expression-annotations#58]
Some other funny subject cases that came in (following new normality rules #55 and #54):

- what if subjects were reported to be cocaine users (5y before death)? 
>>> example: ID 590922 (died from Cerebral Vascular Accident, and suffered from dementia and schizophrenia): i would have discarded only brain tissue.... but  this is a case of drug use.... how to proceed?
- what if subjects were reported to abuse from prescription pills, but the cause of death is not directly linked to drug abuse (example: ID 590955, formally died by motor vehicle accident)
- what if the subjects were diagnosed with "non-metastatic cancer" (they don't say where/what type of cancer),  but the cause of death is not directly linked to cancer (example: ID 590934, formally died because of pontine bleed )
- what about subjects suffering from arthritis? it's not specified whether it's rheumatoid or not; thus in the most optimistic case it would only design "articulation inflammation"... how to proceed?
- there are LOADS of subjects suffering from diabetes (type II)... isn't it too restrictive to discard them all?
- what about subjects who have been reported "positive for blood cultures", aka bacteria were found in blood samples? same for subjects  who have been reported "septic", aka bacteria or toxins were found in body fluids. I think that we should discard them, because it could be the sign of a systemic infection

**Comment by mimiblis** [comment]
@aechchiki : as discussed by whatsapp ;-P
(when I put something here, it means all other param have been checked and are ok, that is why I hesitate)
- GTEX-145MO: what do you think of 'unspecified heart disease' (hardy 3), I would throw it away...
- GTEX-1445S: they say 'heart attack', then heart disease, with an underlying cause of GastroIntestinal bleeding (hardy 3) --> ?
- GTEX-13RTJ: resp. failure, with underlying cause = dehydration --> for me keep all?
- GTEX-13O3P: resp. failure due to GI bleeding --> ?
- GTEX-14E6E: je me souviens plus, head trauma on garde aussi le cerveau?
- GTEX-13FHO: end stage liver disease, mais avec DHHRDY de 0?

**Comment by fbastian** [comment]
Pff, your questions are too tough :p Time to get opinion from @marcrr. 

I'd say that, as it concerns only very few individuals, let's stay on the safe side and discard them.

**Comment by fbastian** [comment]
Note that there is a form available, specifying some criteria to be ineligible: http://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/document.cgi?study_id=phs000424.v6.p1&phd=3910

For instance: Does the donor have a history of intravenous drug abuse in the last 5 years? => ineligible

**Comment by marcrr** [comment]
@mimiblis @fbastian I don't think that I'm especially competent to judge these cases... Maybe we should try to speak with an MD at CHUV?
What is DHHRDY by the way?

**Comment by mimiblis** [comment]
@marcrr : DTHHRDY* is the hardy scale created from GTEx which represent mostly the time taken to die... from 0 = dying in less than 10min to 4 = dying in more than 24h from a long illness
do you have someone in mind to contact at CHUV?

**Comment by marcrr** [comment]
@mimiblis for brain, we could contact Bogdan Draganski. For heart, I don't anyone but I can ask.

**Comment by fbastian** [comment]
Let's have a look at the form I linked to first. I think it answers lots of our questions.

**Comment by aechchiki** [comment]
However, there are subjects with history of cocaine use in the past 5 years was NOT tagged "non-eligible" for the GTEx project (I could get the information from one of the columns about medical history). But yeah, I agree we should discard them from our analysis. 

And subjects suffering from diabetes cannot be considered "non-eligible" for the GTEx project  because of the illness... but do diabetes alter gene expression? It seems so, citing some examples: http://circ.ahajournals.org/content/110/11_suppl_1/II-280.full and http://www.ncbi.nlm.nih.gov/pubmed/23469233 .....

**Comment by fbastian** [comment]
*intravenous* drug *abuse*. Cocain is OK apparently.

**Comment by aechchiki** [comment]
Thanks!
(btw, cocaine can also be used as intravenous drug: http://luxury.rehabs.com/cocaine-addiction/shooting/ )

**Comment by fbastian** [comment]
Haha, all these wonderful things that we're learning :p

**Comment by marcrr** [comment]
I was recommended to contact Katarzyna Michaud, who does forensic medicine and knows well people dying for all kinds of reasons:
https://applicationspub.unil.ch/interpub/noauth/php/Un/UnPers.php?PerNum=45089&LanCode=37&menu=coord
