### ISSUE TITLE
Update to GTEx phs000424.v6.p1

### ISSUE THREAD

**Issue by fbastian** [BgeeDB/expression-annotations#59]
See http://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs000424.v6.p1

* From now on, please use the updated files for your annotations (folder `annotation/GTEx_ phs000424.v6.p1/` on our private 'rxtx')

* Some existing subjects were updated, check the file `annotation/diff_GTEx_Subject_Phenotypes.GRU.txt` in our private 'rxtx'. dbGaP_Subject_ID: 

    985244
    984933
    984974
    985164

* New subjects were added, I added them to the annotation file, dbGaP_Subject_ID: 

    1270588
    1270589
    1270590
    1270591
    1270592
    1270593
    1270594
    1270595
    1270596
    1270597
    1270598
    1270599
    1270600
    1270601
    1270602
    1270603
    1270604
    1270605
    1270606
    1270607

(BTW, I realize that the column `phv00169061.v5.p1.c1` was incorrectly copied by me, so we should remove it I guess)

**Comment by mimiblis** [comment]
These new subjects: dbGaP is ok from the v6 to our .tsv, but the subjID does not match... shall I correct it? I have annotated them (commit 8b3e3af)

**Comment by aechchiki** [comment]
We are then using the identifier reported in the "dbGaP_Subject_ID" column to refer to individuals :)

**Comment by ANiknejad** [comment]
is there still an issue here?

**Comment by ANiknejad** [comment]
please answer ;-)

**Comment by aechchiki** [comment]
Nope, it's okay.... we fixed this ^.^

**Comment by ANiknejad** [comment]
again, thank you! I close the issue
