### ISSUE TITLE
GTEx normality - Subjects medical history

### ISSUE THREAD

**Issue by aechchiki** [BgeeDB/expression-annotations#61]
I report here some interesting columns concerning the subjects medical history (beyond the "serology" column series) that might help us to decide which individuals should be included and which should be discarded:
(I checked the listed columns for subjects 590920 (row n.1) - 984928 (row n.285), and reported in GTEx_subject_annots.tsv the parameters for which the individual was found to be positive, value 1 )

- BS: Amytrophis Lateral Sclerosis  
- BT: alzheimer  
- BV: arthritis  
- BW: ascites (abdominal fluid accumulation, mainly due to liver disease )  
- BX: asthma 
- BY: detection of bacterial infections (no detail)
- CC: cancer detection in 5y before death
- CE: non-metastatic cancer (no detail) history  in 5y before death
- CF: cellulites (inflammation of skin)
- CI: chronic low-respiratory diseases 
- CH: cocaine abuse in 5y before death
- CJ: chronic respiratory disease 
- CK: cerebrovascular disease/stroke/encephalitis
- CL: dialysis 
- CM: dementia 
- CP: active encephalitis
- CR: influenza
- CS: detection of fungal infection (no detail)
- CV: gonorrhoea
- CW: hepatitis B 
- CX: hepatitis C 
- DC/DD: haemophilia
- DF: ischemic heart disease
- DG: heart disease history
- DH: hypertension 
- DJ: intravenous drug abuse
- DM: lupus 
- DN: liver chronic disease 
- DO: meningitis 
- DX: detection of opportunistic infection (no detail)
- DZ: osteomyelitis 
- EA: prescription pill abuse 
- EB/EC: pneumonia 
- EE: parkinson 
- EF: blood culture shown positive to bacteria (no detail )
- EG: arthritis rheumatoid
- EJ: renal failure 
- EL: schizophrenia
- EM: scleroderma 
- EN: drug abuse signs
- EO: sepsis 
- EV: sex-transmitted diseases (no detail)
- EW: long-term steroid use 
- EX/EY: drug use for non-medical reasons 
- FD: diabetes type I 
- FE: diabetes type II 
- FF: tubercolosis 

@mimiblis will check them as well, and together we will establish some restrictive rules (or less restrictive) to see the subjects can be taken, the ones can be taken except from some organs, and the ones who should really be discarded :)

**Comment by mimiblis** [comment]
I think dementia, when having a stroke should not be a paramter do "delete" one person

**Comment by aechchiki** [comment]
Maybe, at least discard brain tissue from the subject suffering from dementia?

**Comment by mimiblis** [comment]
on my side, that will be a lot
