### ISSUE TITLE
RNAseqLibrary - stageID and anatID review (from check_annot.PROB)

### ISSUE THREAD

**Issue by aechchiki** [BgeeDB/expression-annotations#62]
1. AcarDv:0000004 > the term is reported in the current ontologies (http://developmental-stage-ontologies.googlecode.com/svn/trunk/src/acardv/acardv.obo)
2.  BtauDv:0000005 > the term is reported in the current ontologies (http://developmental-stage-ontologies.googlecode.com/svn/trunk/src/btaudv/btaudv.obo)
3. FBbt:00003004 > can be replaced with UBERON:0000468 (since it's about the "whole body tissue" - and "whole body except reproductive tractus") ?
4. FBdv:00005289 > can be replaced with UBERON:0000068 (embryonic stage? annotation reports 0-24h embryos)
5.  FBdv:00005336 > can be replaced with > UBERON:0000069 (larval stage)?
6. Fbdv:00007078 is not reported being obsolete, but it comes from FlyBase (Drosophila stages couldn't be found on the ususl http://developmental-stage-ontologies.googlecode.com/svn/trunk/src/ ): see http://flybase.org/.bin/cvreport.html?cvterm=FBdv:00007078+childdepth=2
7. GgalDv:0000006 >  the term is reported in the current ontologies (http://developmental-stage-ontologies.googlecode.com/svn/trunk/src/ggaldv/ggaldv.obo)
8. GgorDv:0000006 >  the term is reported in the current ontologies (http://developmental-stage-ontologies.googlecode.com/svn/trunk/src/ggordv/ggordv.obo) 
9. HsapDv:0000001> the term is reported in the current ontologies (http://developmental-stage-ontologies.googlecode.com/svn/trunk/src/hsapdv/hsapdv.obo)
10. MdomDv:0000006 > the term is reported in the current ontologies (http://developmental-stage-ontologies.googlecode.com/svn/trunk/src/mdomdv/mdomdv.obo)
11. MmulDv:0000022 >  the term is reported in the current ontologies  (http://developmental-stage-ontologies.googlecode.com/svn/trunk/src/mmuldv/mmuldv.obo) 
12. MmusDv:0000003 >  the term is reported in the current ontologies  (http://developmental-stage-ontologies.googlecode.com/svn/trunk/src/mmusdv/mmusdv.obo)
13. MmusDv:0000110 >  the term is reported in the current ontologies  (http://developmental-stage-ontologies.googlecode.com/svn/trunk/src/mmusdv/mmusdv.obo)
14. OanaDv:0000004 > the term is reported in the current ontologies (http://developmental-stage-ontologies.googlecode.com/svn/trunk/src/oanadv/oanadv.obo)
15. RnorDv:0000015 > the term is reported in the current ontologies (http://developmental-stage-ontologies.googlecode.com/svn/trunk/src/rnordv/rnordv.obo) 
16. SscrDv:000000  > the term is reported in the current ontologies (http://developmental-stage-ontologies.googlecode.com/svn/trunk/src/sscrdv/sscrdv.obo)

17.UBERON:0003270 > can be replaced by UBERON:0001383 (http://www.ontobee.org/browser/rdf.php?o=UBERON&iri=http://purl.obolibrary.org/obo/UBERON_0001383) - "has_alternative_id: UBERON:0003270"
18. UBERON:0019249 (2-cell stage embryo) > the term is reported in Uberon... (http://www.ontobee.org/browser/rdf.php?o=UBERON&iri=http://purl.obolibrary.org/obo/UBERON_0019249)
19. UBERON:0019251 (4-cell stage embryo)  > the term is reported in Uberon... (http://www.ontobee.org/browser/rdf.php?o=UBERON&iri=http://purl.obolibrary.org/obo/UBERON_0019251)

Source for dev stages: http://developmental-stage-ontologies.googlecode.com/svn/trunk/src/ 
Source for drosophila dev stages: http://flybase.org/.bin/cvreport.html?cvterm=FBdv:00007012+childdepth=2
Source for anatomy IDs: http://www.ontobee.org/browser/index.php?o=UBERON

(Shall we change our sources maybe?)

**Comment by fbastian** [comment]
The source for dev stages is now https://github.com/obophenotype/developmental-stage-ontologies, sorry but I think there should be some differences :/

Source for FBbt and FBdv: https://github.com/FlyBase/drosophila-anatomy-developmental-ontology
But I guess it should be similar to what you used. 

For Uberon, it's often simpler to directly look into the ontology, ontobee is not updated very often: http://berkeleybop.org/ontologies/uberon/ext.obo

**Comment by fbastian** [comment]
Also, please note that some stages in FBdv are asynchronous, because they do not occur at the same time in the embryo, such stages should be avoided for annotations, e.g.: "The asynchronous nature of cycle 15 divisions means that this is not very useful for annotating stage. If possible a standard embryonic stage should be used instead."

See comment of FBdv:00007011: "The first 13 cycles are synchronous throughout the embryo and occur their timing relative to other developmental processes is invariant. Later nuclear division cycles are asynchronous across the embryo although may be more locally synchronized.". 

So all embryonic cycles starting with 14th cycle are asynchronous.

**Comment by aechchiki** [comment]
I checked the dev stages source you suggested, and the following terms are reported in the current [species].obo file: 

- AcarDv:0000004 > the term is reported in the current ontologies (https://github.com/obophenotype/developmental-stage-ontologies/blob/master/src/acardv/acardv.obo)
- BtauDv:0000005 > the term is reported in the current ontologies (https://github.com/obophenotype/developmental-stage-ontologies/blob/master/src/btaudv/btaudv.obo)
- GgalDv:0000006 > the term is reported in the current ontologies (https://github.com/obophenotype/developmental-stage-ontologies/blob/master/src/ggaldv/ggaldv.obo)
- GgorDv:0000006 > the term is reported in the current ontologies (https://github.com/obophenotype/developmental-stage-ontologies/blob/master/src/ggordv/ggordv.obo)
- HsapDv:0000001> the term is reported in the current ontologies (https://github.com/obophenotype/developmental-stage-ontologies/blob/master/src/hsapdv/hsapdv.obo)
- MdomDv:0000006 > the term is reported in the current ontologies (https://github.com/obophenotype/developmental-stage-ontologies/blob/master/src/mdomdv/mdomdv.obo)
- MmulDv:0000022 > the term is reported in the current ontologies (https://github.com/obophenotype/developmental-stage-ontologies/blob/master/src/mmuldv/mmuldv.obo)
- MmusDv:0000003 > the term is reported in the current ontologies (http://developmental-stage-ontologies.googlecode.com/svn/trunk/src/mmusdv/mmusdv.obo)
- MmusDv:0000110 > the term is reported in the current ontologies (https://github.com/obophenotype/developmental-stage-ontologies/blob/master/src/mmusdv/mmusdv.obo)
- OanaDv:0000004 > the term is reported in the current ontologies (https://github.com/obophenotype/developmental-stage-ontologies/blob/master/src/oanadv/oanadv.obo)
- RnorDv:0000015 > the term is reported in the current ontologies (https://github.com/obophenotype/developmental-stage-ontologies/blob/master/src/rnordv/rnordv.obo)
- SscrDv:0000000 > the term is reported in the current ontologies (https://github.com/obophenotype/developmental-stage-ontologies/blob/master/src/sscrdv/sscrdv.obo)
- Fbdv:00007078 > the term is reported in the current ontologies (https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/blob/master/fbdv/releases/fbdv.obo)

**Comment by fbastian** [comment]
It doesn't matter, the pipeline will automatically map to Uberon using the xref.

**Comment by aechchiki** [comment]
I checked the uberon source you suggested, and the following terms are reported (and non-obsolete) in the current  file: 

-  UBERON:0003270
-  UBERON:0019249
- UBERON:0019251

**Comment by aechchiki** [comment]
Same for:
- FBbt:00003004

For  FBdv terms, I am waiting for @ANiknejad's and/or @mimiblis  intervention :)

**Comment by mimiblis** [comment]
will do at the end of the week

**Comment by ANiknejad** [comment]
aechchiki commented 2 days ago 
FBbt:00003004 > can be replaced with UBERON:0000468 (since it's about the "whole body tissue" - and "whole body except reproductive tractus") ?
-----
By default, I wont annotate both structures the same term, one is missing a part of the organism and then to annotate to the root anatomical structure

FBbt:00003004 (adult) is already correctly xref of UBERON:0007023
name: adult organism
and this annotation is fine for 'whole body tissue', I guess, if the stage if for a adult fly

UBERON:0000481
name: multi-tissue structure
xref: FBbt:00007010 (multi-tissue structure)

should be the correct term for '"whole body except reproductive tractus", no?
Thoughts?

**Comment by ANiknejad** [comment]
4.FBdv:00005289 > can be replaced with UBERON:0000068 (embryonic stage? annotation reports 0-24h embryos)

UBERON:0000068
name: embryo stage
xref: FBdv:00005289

No needs, will be done automatically, see Fred's comment

**Comment by fbastian** [comment]
Maybe, if the species-specific term used in the xref has exactly the same meaning as the Uberon term (so, xref not supposed to evolve), it is good to update the annotation. But not indispensable.

**Comment by ANiknejad** [comment]
5.FBdv:00005336 > can be replaced with > UBERON:0000069 (larval stage)?

Again, no needs, but this is a tricky annotation, see

https://github.com/obophenotype/uberon/issues/522

UBERON:0000069
name: larval stage
xref: FBdv:00005336 (larval stage)

AND

UBERON:0004730
name: instar larval stage
xref: FBdv:00005336 (larval stage)

**Comment by ANiknejad** [comment]
6.Fbdv:00007078 is not reported being obsolete, but it comes from FlyBase

Here the link to the source, I updated the wiki....that should soon move into github...http://wiki.isb-sib.ch/mrrwiki/Expression_data_annotation

https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/blob/master/fbdv/releases/2015-07-02/fbdv.obo

**Comment by ANiknejad** [comment]
Fred said:
For Uberon, it's often simpler to directly look into the ontology, ontobee is not updated very often: http://berkeleybop.org/ontologies/uberon/ext.obo

I agree, but ext.obo or composite-metazoan?
http://berkeleybop.org/ontologies/uberon/composite-metazoan.obo

see
https://github.com/obophenotype/uberon/issues/705

**Comment by ANiknejad** [comment]
17.UBERON:0003270 > can be replaced by UBERON:0001383

yes, please use UBERON:0001383

[Term]
id: UBERON:0001383
name: muscle of leg
namespace: uberon
alt_id: UBERON:0003270

**Comment by fbastian** [comment]
Use composite-metazoan.obo, you really get absolutely everything in it.

**Comment by aechchiki** [comment]
Annotation updated: 
- FBbt:00003004 > FBbt:00007010 (multi-tissue structure) if sample anatomy info reported: "carcass minus reproductive tractus" (note: FBbt:00003004 annotation unchanged if anatomy info reported "whole flies"/"whole body"
- UBERON:0003270 (skeletal muscle of leg) > replaced by UBERON:0001383 (muscle of leg)

commit hash: ce8502fd9f964d2e10bcec965e7b4526c84c4de3

**Comment by fbastian** [comment]
There is also a problem with `XAO:1000088` that I don't see listed here. It corresponds to `oocyte stage VI`, so I guess that per our policy, this should be annotated to the mother's age, not to an oocyte developmental stage?

**Comment by aechchiki** [comment]
For the moment, I updated the XAO:1000088 with its xref XtroDv:0000094. Hope it's better now. 

Also, I didn't change annotation according to the mother's stage because  (in GEO and in paper) all info that I could find is on the oocytes stage, not on the female age... Btw, oocytes seem to be retrived from "adult females" (Source: http://faculty.plattsburgh.edu/donald.slish/oocyte1.html ), so we could map it as "adult frog stage" - XtroDv:0000084.... But I am waiting for @ANiknejad 's opinion.

Also,  @mimiblis, can you find some additional info on mother's stage (in paper/GEO)?

**Comment by mimiblis** [comment]
I will have a look at it tomorrow morning, no problem @aechichiki

**Comment by aechchiki** [comment]
Following discussion with Fred, I mapped the oocytes to "adult  frog stage", XAO:1000093.

Hash: a9b2389ac35b49f4ddbfcd47146c4c4995c4835b

**Comment by ANiknejad** [comment]
explanations here: we have a structure, an ovocyte (= egg) at a specific developmental stage (oocyte stage VI) not present in the developmental stage ontology of the entity (here Xenopus (female)). So we annotate the structure (egg) at the adult stage
