### ISSUE TITLE
GTEx normality - Current status

### ISSUE THREAD

**Issue by aechchiki** [BgeeDB/expression-annotations#64]
Following information on cause of death (#55), serology information (#54) and medical history (#61), @mimiblis and I would like to report the following status for the current 571 GTEx subjects (AME: 283 + ANE: 288 ) :
- YES: 166 (AME: 70 + ANE: 96) -> ~ 29%
- NO:  123 (AME: 73 + ANE: 50) -> ~ 22%
- PENDING: 284 (AME: 140 + ANE: 144) -> ~49%

Among the "PENDING" patients, we report the following cases (% are calculated on the whole dataset): 
- diabetis: 71 (AME: 69 + ANE: 2) -> ~12% 
- dementia: 57 (AME: 4 + ANE: 53) -> ~10%
- arthritis: 34 (AME: 33 + ANE: 1) -> ~ 6%
- infections (fungal/bacterial/opportunistic): 36 (AME: 25 + ANE:11) -> ~ 6%
- cancer/non-metastatic cancer detection: 22 (AME: 14 + ANE: 8) -> ~4%
- gonhorea: 9 (ANE) -> ~2%
- schizophrenia: 9 (AME)  -> ~2%
- ascites: 11 (AME: 7 + ANE; 4) -> ~2%
- parkinson: 1 (AME) -> <1%
- alzheimer: 2 (ANE) -> < 1%
- sepsis: 7 (AME) ->  ~1%
- cellulites: 3 (AME) -> <1%
- sclerosis: 2 (AME) -> <1%
- osteomyelitis: 4 (AME) -> ~1%
- heart disease (not cause of death, column DF-DG): 118 (47 AME + 71 ANE) --> ~21%
- chronic resp disease: 106 (52 ANE + 54 AME) --> ~19%

Obviously, we cannot discard all those cited "PENDING" patients (this would mean, excluding more than 90% of the "PENDING"!). 

We think that a good compromise would be to:
-  completely discard subjects with: cancer, sclerosis, gonhorrea, sepsis, infections. Tthis would mean: 82 subjects (~30% of the current "pending", aka15% of the whole ) tagged as "NO".
- discard brain and nervous tissue from subjects with: dementia, alzheimer, parkinson.  
- discard liver tissue from subjects with: ascites.
- discard bone tissue from subjects with: osteomyelitis.
- discard skin tissue from subjects with: cellulites.

Furthermore:
- discard heart tissue from subjects with: heart disease (NOT heart failure!)
- discard lungs tissue from subjects with: pneumonia, chronic respiratory disease
- discard brain tissue from subjects with: AVC and hardy scale 3 or 4 (as we already discussed)
- discard liver tissue from subjects with: liver disease 
- discard kidney tissue from subjects with: renal disease/failure

We still don't know how to deal with subjects suffering from diabetes and arthritis. We cannot discard them all for sure (too many! ~37% of "pending", aka ~19% of the whole! )

Waiting for your advice ;)

**Comment by mimiblis** [comment]
Nice summary of what we checked ;-)

**Comment by mimiblis** [comment]
I do not agree with discarding heart tissue from patients with heart disease when it is not cause of death...--> it would discard 1heart/5

**Comment by aechchiki** [comment]
Follow-up of Bgee meeting today: 
- discard subjects suffering from diabetes type I (autoimmune disease); 
- we're gonna examine "pending" subjects case by case, next week (with Anne and Marc): be sure the info on every subject is well reported in the "Explanation for status" column

**Comment by mimiblis** [comment]
Thanks amina

**Comment by ANiknejad** [comment]
I would consider as OK all PENDING subjects with these explanations:

cardiac arrest (hardy 2)
AVC of hardy 2
AVC (hardy 2)


@marcrr 
4-point Hardy Scale  value:
 2) Fast death of natural causes: Sudden unexpected deaths of people who had been reasonably healthy, after a terminal phase estimated at < 1 hr (with sudden death from a myocardial infarction as a model cause of death for this category)

**Comment by ANiknejad** [comment]
I would exclude

GTEX-13FHO
end stage liver disease (hardy 0)

@marcrr
4-point Hardy Scale value:
0) Ventilator Case: All cases on a ventilator immediately before death.

**Comment by ANiknejad** [comment]
Note that in the file we have currently:

GTEX-144GN	PENDING	AVC (hardy 0) + fungal infection

GTEX-13SLX-3126-SM-5S2Q5	YES	AVC (hardy 0) + dialysis + fungal infection

**Comment by ANiknejad** [comment]
I would exclude all 'dialysis' subjects, I guess

**Comment by marcrr** [comment]
1- I agree with the calls of @ANiknejad so far.
2- I agree with the "good compromise" of @aechchiki at the top of this page.
3- I disagree with arguments of the type "if we follow this or that rule, we exclude too many samples"; we're not in the business of making GTEx's efforts worthwhile, but of providing consistent curated data. If some calls lead to 20% of heart samples, so be it in my opinion.
