### ISSUE TITLE
check_annot.PROB --> E-MTAB-2950

### ISSUE THREAD

**Issue by mimiblis** [BgeeDB/expression-annotations#65]
Have modified the sample names, with what we have discussed on a certain day
f.E: 
- s_1cell.WE --> ERR632211_1 for tech rep 1
- s_1cell.WE --> ERR632211_2 for tech rep 2

hope this is okay

hash: b56da1f

**Comment by fbastian** [comment]
So you assigned these IDs based on the file names present on the SRA FTP? I guess this is not what we usually do, am I correct? 
@smoretti: how files are currently downloaded? I guess that the current pipeline convert GSM IDs to SRA IDs, then get the download link from SRA? It is not meant to use directly the FTP link, right?

@mimiblis: did you get a confirmation that they were technical replicates? https://github.com/BgeeDB/expression-annotations/issues/47#issuecomment-143684925

**Comment by mimiblis** [comment]
these names are coming from: http://www.ebi.ac.uk/arrayexpress/files/E-MTAB-2950/E-MTAB-2950.sdrf.txt 
I do not know if you remember, but we discussed this with Anne back then.

Nope did not get a confirmation and BTW I have to correct the organ (#47), I think I have not commited it. 

Do you want me to # these lines until we are sure of evthg?

**Comment by fbastian** [comment]
Yes, please correct the organ, then comment them. As well as the corresponding experiment if there is no library left. 
Thanks!

**Comment by mimiblis** [comment]
corrected: da5d15e

**Comment by ANiknejad** [comment]
Thank you, Angélique
