### ISSUE TITLE
not contiguous experiment [GSE43520] (split in different part of the file)

### ISSUE THREAD

**Issue by smoretti** [BgeeDB/expression-annotations#67]
GSE43520 looks to be listed at different places (not contiguous) in the RNASeqLibrary.tsv file

**Comment by aechchiki** [comment]
Please refer to my comment on issue #68. 
(I commented those lines for now)

**Comment by ANiknejad** [comment]
it was because news GSM were present at time we re-checked the GSE experiment...however the EXPERIMENT_STATUS was already annotaed as 'total'...
