### ISSUE TITLE
empty organId for some entries

### ISSUE THREAD

**Issue by smoretti** [BgeeDB/expression-annotations#68]
Warning: empty organId [GSE43520-GSM1196058]
Warning: empty organId [GSE43520-GSM1196059]
Warning: empty organId [GSE43520-GSM1196060]

**Comment by aechchiki** [comment]
These are new GSMs from already annotated GSE. I commented those lines, waiting for @ANiknejad's or @mimiblis's advice (I couldn't retrieve organ source in GEO/paper). 
Hash: 3f36608b4a7a5c6ce467e5c17f431026ca7bf53a

**Comment by mimiblis** [comment]
GSM1196058 seems to be human placenta
GSM1196059 mouse placenta
GSM1196060 mouse placenta

is this what you need @aechchiki ?

**Comment by smoretti** [comment]
No, the field UberonId (mandatory) was empty for those 3.

**Comment by mimiblis** [comment]
oh okay I see. @aechchiki would this be the thing you are looking for?
UBERON:0001987 placenta

**Comment by smoretti** [comment]
Yes, something like that.

**Comment by aechchiki** [comment]
Fixed: added UberonID for organs. samples were mapped on mother's information, placenta (thanks @mimiblis ) being a mother-derived tissue (age: "adult", sex: "F")
The rows are still commented, waiting for Anne's agreement on annotation.

Hash: 2d72f45b18304baa2758545c5b54e40ff9d8346f

**Comment by smoretti** [comment]
OK, perfect for me.
Thanks

**Comment by ANiknejad** [comment]
Many thanks, yes, mother-derived structure, so correctly annotated on placenta and adult stages, please then remove the comment to let the lines be considered by the pipeline

**Comment by aechchiki** [comment]
Done, 2807c1743450ba741dc4a03f9b32f7c21115acad :)

**Comment by ANiknejad** [comment]
great, thank you!
