### ISSUE TITLE
Overall GTEx normality

### ISSUE THREAD

**Issue by ANiknejad** [BgeeDB/expression-annotations#71]
GTEx Uberon mapping discrepancy (summary of #57)
(nb: examples below are from the original file, so samples given as example should not be present in the final file, due to **selective check for normality, see posts below**)

To check Uberon mapping, we consider columns 
SMSMPSTE  Tissue Location
SMTSD  Tissue Type
and also column SMPTHNTS (Pathology notes) if some complementary information is available

Note that there are targets defined by GTEx in at least 2 GTEx instruction files

http://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/document.cgi?study_id=phs000424.v6.p1&phd=3910#sec2.1

http://biospecimens.cancer.gov/resources/sops/docs/GTEx_SOPs/BBRB-PR-0004-W1%20GTEx%20Tissue%20Harvesting%20Work%20Instruction.pdf

and sometimes the pathologist does sampling a more precise structure or even another structure, and reports this information in SMPTHNTS notes, but sounds like GTEx still focus on the target to do Uberon mapping and so does miss some precision or even does mismatch.

1.- example of **wrong** annotation, not confident annotation:
sample = GTEX-RVPV-0226-SM-2TF6W
                   SMSMPSTE = Radial Artery
                   SMTSD = Artery - Tibial
---> Uberon mapping made on UBERON:0007610 tibial artery

2.- example of annotation **more precise** than expected by the available information
2.-1
mapping done on precise term 'ascending' while information is only 'thoracic'
sample = GTEX-13O21-0426-SM-5K7VR
                   SMSMPSTE = Thoracic regions (non-atherosclerotic)
                   SMTSD = Artery – Aorta
---> Uberon mapping made on UBERON:0001496 ascending aorta
in view of the information given by the pathologist, the mapping should instead be done on UBERON:0001515 thoracic aorta, but the Aqua Kit asked for
'Aorta	Ascending aorta; Other thoracic region; ' and so the GTEx mapping was done on the 'ascending aorta'
same issue with sample =  GTEX-RVPV-0226-SM-2XU9L
2.-2
mapping done on precise term 'breast epithelium' while information is only 'breast'
sample = GTEX-1117F-2826-SM-5GZXL
                   SMSMPSTE = left
                   SMTSD = Breast - Mammary Tissue
---> Uberon mapping made on UBERON:0008367 breast epithelium
2.3
all 'minor salivary glands' were GTEx mapped on 
UBERON:0006330 anterior lingual gland 
while no information about 'lingual' structure is available from pathologists and the instruction was to remove from 'inner surface of lower lip' (error due to a mix between 'lip' and 'lingual' terms?)
---> Uberon mapping corrected, and made on UBERON:0001830 minor salivary gland

3.- examples of annotation **less precise** than expected by the available information
3.-1 due to contradictory information in the file between the 'Aqua Kit' instructions and the more precise notes from the pathologist ('entire' versus 'anterior') 
sample = GTEX-OXRN-2626-SM-48TBX
                SMPTHNTS  = Anterior pituitary. 6.5x5.7mm
                SMSMPSTE = Entire
                SMTSD = Pituitary
---> Uberon mapping made on UBERON:0000007 pituitary gland, while 'anterior pituitary' is in fact adenohypophysis. We decided to consider the notes from the pathologist as reflecting the actual sampling, so here the mapping should instead be done on UBERON:0002196 adenohypophysis

3.-2 due to mapping error
sample = GTEX-11GSP-0011-R11b-SM-5NQ7V
               SMSMPSTE = NA
                SMTSD = Brain - Cerebellar Hemisphere
---> Uberon mapping made on UBERON:0002037 cerebellum, while a more precise Uberon term is available, UBERON:0002245 cerebellar hemisphere

4.- Example of annotation using a **close but not accurate** Uberon term (because no other choice!)
GTEx target
"Gastroesophageal junction Preferred Location: Gastroesophageal junction: the lowest portion 
of the esophagus just proximal to the stomach. Obtain only muscularis propria; discard mucosa; avoid stomach"
are all GTEx mapped on UBERON:0004550 gastroesophageal sphincter,
while the picture in the instruction clearly refers to a more large area, and nowhere is the term 'sphincter' used in the instructions. 
**Bgee improvement thanks to creation of more precise term**: we asked Uberon for a new anatomical term, and Uberon provides now:
UBERON:0035841
+name: esophagogastric junction muscularis propria

Note.
http://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/document.cgi?study_id=phs000424.v6.p1&phd=3910#sec2.1

GTEx gives instructions to sample brain tissues, but there is an **inconsistency in the description of the target**:

Brain - cerebellum	Right cerebral frontal pole; Other: 

There is no 'frontal pole' in the cerebellum, but in the cerebrum (=cerebral hemisphere).
This leads pathologists to sample different tissues:
- Right Cerebellum 
- cerebellum  
- Cerebral frontal pole -right 

As a result, many mapping errors are present:
914542	GTEX-QMR6-1326-SM-32PLB	4   ~6x5mm aliquots	Cerebral frontal pole -right	Brain	Brain - Cerebellum		2037	cerebellum 

860469	GTEX-R55F-1226-SM-2TWB5	4 pieces up to 5x4 mm; good Purkinje cells	Cerebral frontal pole -right	Brain	Brain - Cerebellum		2037	cerebellum

**Comment by ANiknejad** [comment]
@aechchiki 
@mimiblis 

please complete the issue with the following posts:
- procedure for subject eligibility in Bgee, with list of GTEx columns that we check during this procedure
- procedure for samples eligibility in Bgee, with list of GTEx columns that we check during this procedure

**Comment by ANiknejad** [comment]
....I was expecting your summary here ?

@mimiblis 
@aechchiki

**Comment by mimiblis** [comment]
Yep Coming this morning we had to make sûre if certain point.

**Comment by ANiknejad** [comment]
ok ;-)

**Comment by mimiblis** [comment]
GTEx - SAMPLE - normality check:
To sort "good" samples from the "bad" ones, we checked columns:
SMPTHNTS - free text (from the person who analyzed the sample)

1. a SAMPLE is "good" when:
  - there is nothing specified it SMPTHNTS
  - the sample is labelled as well preserved, well trimmed, well ...
  - the sample contains <=10% of foreign tissue (e.g.: skeletal muscle + 10% total adipose)
  - displasia or atrophy appears in SMPTHNTS without any other "sickness" (because those two are mostly normal --> related to the age of the patient)

2. a SAMPLE is "bad" when:
  - the sample contains more that 10% of foreign tissue (e.g.: salivary gland + 50% of skeletal muscle, nerve and vessels
  - when it is under inflammation (whether inflammation appears, or it is most of the time specified gastritis, chronic vaginitis, Hashimoto (thyroiditis) --> sick tissue
  - when metaplasia (first step before cancer)
  - when there is autolysis (any score) --> it means tissue is getting changed, thus RNAseq also
  - when there is adenoma (benign tumour, most of the time subject is viable, but RNAseq not normal)
  - when the sample is poorly preserved (same as autolysis)
  - when there is labelling problem (2 pieces, one is prostata (target), one is parathyroid)

3. a SAMPLE is "pending" when:
  - there are some weird things that cannot be solved with the preceding points (e.g.: LDACC alert)

@aechchiki: I think this is all? normally we are now able to put good and bad to all the sample (except exceptions). If you are ok with this message just remove this "phrase qui ne servira a rien".

**Comment by aechchiki** [comment]
GTEx - subjects, normality check. 

Following discussions in #64:

- completely discard ("NO") subjects: 
    - cancer
    - sclerosis
    - gonhorrea
    - sepsis
    - infections
    - diabetes type I 
    - dialysis
    - end-stage diseases (liver, kidney)

- selectively discard ("PENDING") subjects: 
    - brain and nervous tissue from subjects with: dementia, alzheimer, parkinson, AVC and hardy scale 3 or 4 
    - liver tissue from subjects with: ascites,  liver disease
    - bone tissue from subjects with: osteomyelitis.
    - skin tissue from subjects with: cellulites.
    - heart tissue from subjects with: heart disease (NOT heart failure!)
    - lungs tissue from subjects with: pneumonia, chronic respiratory disease
    - kidney tissue from subjects with: renal disease/failure

**Comment by ANiknejad** [comment]
could you please define here the rules used regarding BMI index for subject eligibility?

**Comment by aechchiki** [comment]
done (see edit in my comment up here ^)

**Comment by ANiknejad** [comment]
In GTEx_samples-track.tsv
could you please tag the column to understand which column is a original GTEx column 
and which is Bgee column (info put by Bgee annotators)

'Annotation subject status'
is typically a 'Bgee' column, (--> Bgee Annotation subject status)
while 'Annotation subject info' is less clear: reports info from GTEx AND from Bgee, example: 'BMI out of range' is a Bgee tag...
Maybe to re-name this column: Bgee Annotation subject info, based on GTEx subject info

Sorry to be so 'emmerdeuse' mais nécessaire ;-)

**Comment by mimiblis** [comment]
Amina since all this is on your shoulder I can do some other "final" annotations if you need ; -)

**Comment by ANiknejad** [comment]
close so far, on going 'review_of_GTEx_annotations_FILES' done by Amina
