### ISSUE TITLE
RNASeqLibrary.tsv, replace GSM by SRX

### ISSUE THREAD

**Issue by ANiknejad** [BgeeDB/expression-annotations#72]
Sebastien already automatically replaced GSM by SRX for the next coming release, but for RNA-seq experiments on new taxons (not considered in this release), we have to manually replace GSM by SRX.
example:
http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM1055014
bottom of the page, we will get  	SRX211604
Please replace in the RNASeqLibrary.tsv

(Total of items, about 200)

**Comment by fbastian** [comment]
We can do that automatically, don't bother.

**Comment by mimiblis** [comment]
Okok

**Comment by ANiknejad** [comment]
I was wondering but in fact Sebastien is now considering only automatically changes for new release, and he does not want to go back to that once done,  I understand his position

**Comment by fbastian** [comment]
I wanted to quickly write a script to do it for you, but I couldn't find the time, sorry :/ So yes, please update manually.

**Comment by ANiknejad** [comment]
@mimiblis 
@aechchiki 

so, something to do once we are finished with GTEx

**Comment by mimiblis** [comment]
Okax :-)

**Comment by ANiknejad** [comment]
done
