### ISSUE TITLE
tricky GTEx colon mucosa annotation

### ISSUE THREAD

**Issue by ANiknejad** [BgeeDB/expression-annotations#73]
This is not clear which colon 'muscularis' is the target: muscularis mucosa OR muscularis propria
Look at 
http://www.histology.leeds.ac.uk/digestive/GI_layers.php

1271796	GTEX-WH7G-1426-SM-4LVMU

'6 pieces, up to 10x4mm; All have muscularis propria (our target) but 5 of 6 have (unwanted) mucosa'
-> this is mapped on 1159	sigmoid colon
If this is realy 'muscularis propria', should be mapped on new Uberon term 
id: UBERON:0035805
+name: muscle layer of sigmoid colon

But others guys talk about only 'muscularis'
1267692	GTEX-11EQ9-1526-SM-5PNY7
6 pieces, muscularis, adherent rim of serosa/fat up to ~1.5mm

--> and this is also mapped on 1159	sigmoid colon

1267342	GTEX-111YS-1826-SM-5GIEP
6 pieces; muscularis (target) with up to 1 mm external fat
--> and this is also mapped on 1159	sigmoid colon

For esophagus, the target sounds to be 'muscularis mucosa':

1268726	GTEX-12WSL-1526-SM-5GCP8
5 pieces; well dissected mucosa with prominent muscularis mucosae
mapped on 6920	esophagus squamous epithelium

**Comment by mimiblis** [comment]
this is for me, colon is in my part. I have seen these things, so I will carefully go through it again to put BAD -GOOD uberon annotations depending on what is sampled.

**Comment by ANiknejad** [comment]
many thanks, Angélique

**Comment by ANiknejad** [comment]
http://biospecimens.cancer.gov/resources/sops/docs/GTEx_SOPs/BBRB-PR-0004-W1%20GTEx%20Tissue%20Harvesting%20Work%20Instruction.pdf

Transverse colon: target is the full thickness of the colonic wall, i.e., mucosa and muscularis propria
--> to annotate on UBERON:0001157	transverse colon
ok, checked done in  master/annotations/rna_seq/RNASeqLibrary.tsv and this one is OK

Sigmoid colon: Obtain only muscularis propria
--> to annotate on UBERON:0035805 muscle layer of sigmoid colon 
--> PLEASE do correction in  master/annotations/rna_seq/RNASeqLibrary.tsv
The original file gives infoOrgan 'muscularis-colon-sigmoid' (from 2 different columns), please report this info

**Comment by ANiknejad** [comment]
great, many thanks! I close the issue
