### ISSUE TITLE
useful Uberon terms for GTEx annotations

### ISSUE THREAD

**Issue by ANiknejad** [BgeeDB/expression-annotations#74]
UBERON:0009853
name: body of uterus
Corpus	Normal	Uterus		Uterus	995	uterus

UBERON:0004533
name: left testis

UBERON:0004534
name: right testis

UBERON:0001626
name: left coronary artery

UBERON:0001625
name: right coronary artery

UBERON:0001161
name: body of stomach

UBERON:0002118
name: right ovary
--> to replace all 
Right	Normal	Ovary		Ovary	2119	left ovary
!!!!

UBERON:0003454
name: small intestine Peyer's patch
(example. for 1268034	GTEX-11P82-0826-SM-5P9GU ?)

UBERON:0001379
name: vastus lateralis
(example: for 1273533	GTEX-ZVZO-0326-SM-5HL4N)

UBERON:0013755
name: arterial blood
(example: for 914908	GTEX-TMZS-0002-SM-3G3S5
to correct '13756	venous blood' for sample  blood of Left Radial Artery)

UBERON:0001235
name: adrenal cortex
(example: for 1271376	GTEX-14DAQ-1826-SM-5S2VV)

UBERON:0001234
name: left adrenal gland

UBERON:0001233
name: right adrenal gland

follow here new terms requested so far:
https://github.com/obophenotype/uberon/issues/1170

UBERON:0035825       
+name: left adrenal gland cortex
UBERON:0035826       
+name: left adrenal gland medulla
UBERON:0035827
+name: right adrenal gland cortex
UBERON:0035828       
+name: right adrenal gland medulla

Please use
UBERON:0003516
name: hindlimb blood vessel

for dubious information such as below
1109774	GTEX-X88G-0426-SM-47JZ5	0	 
Tissue	2 pieces  ~5mm d.  Adherent fibroadipose tissue, discontinuous, delineated, up to ~2mm	6.8	Popliteal	Normal	Blood Vessel	popiteal	Artery - Tibial	7610	tibial artery

**Comment by ANiknejad** [comment]
914998	GTEX-UJHI-0001-SM-3G3TR
Blood	Right Ventricle

is annotated on 13756	venous blood
and this is correct

However,
1664292	GTEX-XV7Q-0004-SM-4YUWC
Blood Ventricle
is not necessary a 'venous blood', as annotated
In such case, please use the more general term
UBERON:0000178
name: blood

**Comment by ANiknejad** [comment]
regarding discussion this morning, please look at here
http://www.hopkinssjogrens.org/disease-information/diagnosis-sjogrens-syndrome/labial-gland-lip-biopsy/
" The minor salivary glands just under the inner surface of the lip are the most accessible of these glands."

**Comment by ANiknejad** [comment]
Inner surface of lower lip	Normal	Salivary Gland		Minor Salivary Gland	
6330	anterior lingual gland

I guess, should be annotated on 
UBERON:0001830
name: minor salivary gland

**Comment by ANiknejad** [comment]
UBERON:0001515
name: thoracic aorta

for
6 pieces, no significant atherosis	6.3	Thoracic regions (non-atherosclerotic)	Normal	Blood Vessel	Expected time lapse of greater than 20 mins for tissue removal is due to GTEx recovery workflow."	Artery - Aorta	1496	ascending aorta

**Comment by ANiknejad** [comment]
UBERON:0001514
name: descending aorta

for
6 pieces, up to 9x4mm;	9.6	Descending thoracic region, aorta	Normal	Blood Vessel		Artery - Aorta	1496	ascending aorta

**Comment by ANiknejad** [comment]
2 pieces, largely adipose stroma; few ductal/lobular elements, atrophic, are present, rep. ones delineated	7.8	Right	Normal	Breast		Breast - Mammary Tissue	8367	breast epithelium

I was hesitating to transfer on 
UBERON:0001911	mammary gland

but maybe ok on
UBERON:0008367
name: breast epithelium

Remember 'All glands are made up of epithelial cells.'
https://en.wikipedia.org/wiki/Epithelium

**Comment by ANiknejad** [comment]
note that exists
UBERON:0001119
name: right lobe of thyroid gland

but because samples are only 'right thyroid', it is safer to conserve 
2046	thyroid gland

**Comment by mimiblis** [comment]
euhmmm... for the thyroid, I have samples of left thyroid, of thyroid (general) and of right thyroid. So I matched UBERON accrodingly

**Comment by mimiblis** [comment]
for these pituitary samples... they did complete sh*** 
So @ANiknejad , if you could have a look, but my guess is:
  - when they say entire gland to map on UBERON:0000007 : pituitary gland
  - when they precise adenohypophyse (AND we see it is effectively adeno) --> UBERON:0002196 : adenohypophysis
  - when they precise neurohypophyse (AND we see it is effectively neuro) --> UBERON:0002198 : neurohypophysis

**Comment by ANiknejad** [comment]
mimiblis commented 2 days ago

euhmmm... for the thyroid, I have samples of left thyroid, of thyroid (general) and of right thyroid. So I matched UBERON accrodingly

Angélique, are you sure there is the *lobe* of the tyroid (right or left) when they talk about 'right' or 'left' thyroid?

**Comment by ANiknejad** [comment]
@mimiblis 
I agree with your comments on the sh...annotations!
ok for pituitary

for esophagus, I guess, the target is 'mucosa', but:

they annotated on
UBERON:0006920
name: esophagus squamous epithelium
is_a: UBERON:0001976 ! epithelium of esophagus

Because UBERON:0001976 epithelium of esophagus
part_of UBERON:0002469 ! esophagus mucosa

and also WP says:
The mucosa is a stratified squamous epithelium (multiple layers of cells topped by a layer of flat cells)

I guess, we can safely annotate on

UBERON:0002469
name: esophagus mucosa
relationship: part_of UBERON:0001043 ! esophagus
relationship: part_of UBERON:0001096 ! wall of esophagus

Thoughts?

**Comment by ANiknejad** [comment]
@mimiblis 
for Kidney, the target sounds to be 'cortex' but not always successfully sampled.
And we have only few good samples....

So here maybe to annote (as did so far in Bgee for mammals, so for sake of consistency) on:
UBERON:0000082
name: adult mammalian kidney

@fbastian you agree? or you prefer we save at least the positional information (left/right)?
UBERON:0004538 left kidney
UBERON:0004539 right kidney

**Comment by ANiknejad** [comment]
UBERON:0000082 adult mammalian kidney
is_a: UBERON:0002113 ! kidney

UBERON:0004538
name: left kidney
is_a: UBERON:0002113 ! kidney

**Comment by ANiknejad** [comment]
Esophagus, summary (sic!)
Sounds like there are 2 targets
(see http://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/document.cgi?study_id=phs000424.v6.p1&phd=3910#sec2.1)

1.Esophagus - mucosa	Squamous region above GE junction; Other: 					
2.Esophagus -muscularis	Squamous region above GE junction; Other: 

To have 2 distinct items, that means, 
1. is mucosa and contains muscularis mucosa, 
2. is the muscle layer of esophagus (= tunica muscularis oesophageae)

Examples:

1.

931560	GTEX-OIZI-1426-SM-3NB1T	Squamous *mucosa* with *prominent muscularis mucosae* Squamous region, above gastroesophageal junction	Esophagus	Esophagus - Mucosa		6920	esophagus squamous epithelium

--> to annotate on UBERON:0002469
name: esophagus mucosa

2.

931647	GTEX-P78B-1126-SM-3P615	6 pieces,  ~8.5x3 mm. well-oriented specimens.	Squamous region, above gastroesophageal junction	Esophagus	Esophagus - Muscularis		4648	esophagus muscularis mucosa

--> to annotate on
UBERON:0011878 muscle layer of esophagus

**Comment by mimiblis** [comment]
Okay perfect will be donc like this :-)

**Comment by ANiknejad** [comment]
if you agree, yes, but sure, open to discussion

**Comment by mimiblis** [comment]
I ll tell you if for some samples I would not agree ;-)

**Comment by mimiblis** [comment]
@ANiknejad :
concerning oesophagus (y'en a qui pour lui hehe)
Muscularis of  lowest portion of esophagus	Esophagus	Esophagus - Gastroesophageal Junction		4550	gastroesophageal sphincter 
Un cas comme ca --> moi je vois que c'est la muscularis de la portion basse de l'oesophage. Maintenant, j'aimerais savoir si tu penses que c'est ok de dire que la jonction stomacho-oesophagienne on peut annoter sur gastroesophageal sphincter?
Je voulais juste etre sure. pour moi ça colle, mais bon, vaut mieux éviter les erreurs

**Comment by ANiknejad** [comment]
'1109461	GTEX-U4B1-0126-SM-4DXSN	2 pieces, 6x14 & 6x9 mm; largely cortex; 1 piece has'

--> please do not annotate on UBERON:0001235 - adrenal cortex
but on UBERON:0001234
name: left adrenal gland

**Comment by ANiknejad** [comment]
@mimiblis 
Muscularis of lowest portion of esophagus Esophagus Esophagus - Gastroesophageal Junction 4550 gastroesophageal sphincter 

here again the target sounds to be:
Esophagus -muscularis	Squamous region above GE junction;
as defined in 
http://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/document.cgi?study_id=phs000424.v6.p1&phd=3910#sec2.1

So we could either annotate on
UBERON:0011878 muscle layer of esophagus
or on
UBERON:0013473
name: lower esophagus

or...
https://github.com/obophenotype/uberon/issues/1176

waiting for Chris's answer!

**Comment by ANiknejad** [comment]
also
https://github.com/obophenotype/uberon/issues/1177

**Comment by ANiknejad** [comment]
see also #75

**Comment by ANiknejad** [comment]
le mail que je vous avais envoyé:


"On résume:
les instructions GTEx pour prélever les tissus sont ici:
http://biospecimens.cancer.gov/resources/sops/docs/GTEx_SOPs/BBRB-PR-0004-W1%20GTEx%20Tissue%20Harvesting%20Work%20Instruction.pdf

donc  on a

1.esophagus, Squamous region (distal/lower third), at least 4 cm above gastroesophageal  junction
--> 2 targets:
1.1 squamous mucosa : annoté GTEx  6929 esophagus squamous epithelium
mais on a maintenant le nouveau terme UBERON:0035834  lower esophagus mucosa

1.2 muscularis : annoté GTEx  4648 esophagus muscularis mucosa


2.gastroesophageal junction
Gastroesophageal junction: the lowest portion of the esophagus just proximal to the stomach
--> une seule target =  muscularis propria
(terme Uberon demandé, cf
https://github.com/obophenotype/uberon/issues/1182)

annoté GTEx sur 'gastroesophageal sphincter' ça me parait faux
4550  "gastroesophageal sphincter

1.2
 Dans un premier temps, j'ai pensé que la 'muscularis' de esophagus était aussi de la muscularis propria (et donc j'ai obtenu de Chris le nouveau terme 
UBERON:0035833
+name: lower esophagus muscularis layer

mais là, j'ai des doutes...ils demandent de séparer la 'white mucosa from the nonwhite muscularis', et si le morceau est trop épais, il faut l'affiner en partant de l'adventice donc de la partie externe, muscularis propria, vers le centre, et alors il ne resterait que la 'muscularis mucosa', non???

notez au passage la finesse de définiton de 'distal/lower third' par rapport à 'lowest portion'...je rigole, c'est vraiment de quoi se foutre dedans avec des infos pareilles!!!

Voila, open to discussion!"

**Comment by ANiknejad** [comment]
Elucidating the 'gastroesophageal junction' annotation:

http://training.seer.cancer.gov/ugi/anatomy/stomach.html

this reference is the one used in the GTEx document 'Tissue Harvesting Work Instruction'
to let the pathologists sampling the 'Gastroesophageal junction', and in fact this region is the 'cardia' of the stomach (UBERON:0001162 cardia of stomach)
UBERON:0004550
name: gastroesophageal sphincter
relationship: part_of UBERON:0001162 ! cardia of stomach

So it is ok to follow the GTEx annotation on 4550 "gastroesophageal sphincter

**Comment by ANiknejad** [comment]
So please annotate
'Esophagus - Gastroesophageal Junction - Muscularis of  lowest portion of esophagus'

on UBERON:0004550 gastroesophageal sphincter

@mimiblis 
@aechchiki

**Comment by ANiknejad** [comment]
"Esophagus – Mucosa - Squamous region, above gastroesophageal junction"

to annotate on
UBERON:0035834 lower esophagus mucosa

as said in the post above 'le mail que...'

@mimiblis 
( @aechchiki )

**Comment by mimiblis** [comment]
both of last posts are corrected, I even corrected the replicates when it was needeed

**Comment by ANiknejad** [comment]
Sorry, we have now more precise terms from Uberon, thanks to Chris, please see 
https://github.com/obophenotype/uberon/issues/1182#event-491136195

so Esophagus - Gastroesophageal Junction - Muscularis of lowest portion of esophagus

could now be annotated on 
UBERON:0035841
+name: esophagogastric junction muscularis propria

instead of UBERON:0004550 gastroesophageal sphincter

**Comment by mimiblis** [comment]
Good!

**Comment by ANiknejad** [comment]
Good hein pas ...God!

**Comment by mimiblis** [comment]
Nono !  Je trouve cool qu'on a des termes précis.  C'est important. :-)

**Comment by ANiknejad** [comment]
closed (so far..)

**Comment by ANiknejad** [comment]
we conserved the GTEx annotation 
UBERON:0004648	esophagus muscularis mucosa

for samples with information 
Esophagus-Muscularis-Squamous region, above gastroesophageal junction

**Comment by ANiknejad** [comment]
https://github.com/obophenotype/uberon/commit/5e5c6c45849fcb1ac3290c1c4829a73d8fc9648c

we have now a 'lower esophagus' class for 'Squamous region, above gastroesophageal junction' region
