### ISSUE TITLE
Problem in GTEX_selected-samples_annots.tsv

### ISSUE THREAD

**Issue by fbastian** [BgeeDB/expression-annotations#77]
Line 7704 is messed up.

**Comment by mimiblis** [comment]
Euhm okay. Because I saw that thé three last lines are cut and I have notified amina . See #75

**Comment by ANiknejad** [comment]
c'est fini ca?

**Comment by mimiblis** [comment]
yes

**Comment by aechchiki** [comment]
yep ^.^ (the awk script didn't assign any "selected" value because the original file contained no info for the wanted fields)

**Comment by ANiknejad** [comment]
si tu le dis....je vous fais confiance!

**Comment by ANiknejad** [comment]
Back on this file, there are many redundant lines (165) and I wonder if this is not the cause of some miss-reported annotations, as Angélique explained in her last post #85 for UBERON:0002810 ! right frontal lobe?


1267311	GTEX-111FC-3126-SM-5GZZ2	2 pieces	Cerebral frontal pole -right	Brain	Brain - Cortex		1870	frontal cortex 	GOOD	no info	BAD	after discussion	UBERON:0002810 ! right frontal lobe	1	61	3	AME	08.11.2015
1267311	GTEX-111FC-3126-SM-5GZZ2	2 pieces	Cerebral frontal pole -right	Brain	Brain - Cortex		1870	frontal cortex 	GOOD	no info	GOOD	ok		1	61	3	AME	08.11.2015

**Comment by ANiknejad** [comment]
We need to check this redundancy to ensure correct reannotations for other structures

**Comment by mimiblis** [comment]
Normally I checked to have no redundancies in the final rnaseq annotations (rnaseqLibrary.tsv).  I think in one issue that I do not find anymore I asked for someone to check redundancies in rnaseqLibrary.tsv because my eyes were tired. So I do not see the link with cerebral pole.  Anyway I totally forgot that we changed the uberon for this tissue so I do not think redundancies came across that to make me do wrong. It's only me being not careful  enough

**Comment by ANiknejad** [comment]
>So I do not see the link with cerebral pole.
The two lines in GTEX_selected-samples_annots.tsv are different regarding acceptation of GTEx annotation on Uberon: BAD (means to be changed/reannotated) and GOOD (accepted as it) so I was wondering, this can be the source of miss-annoation from our part?

**Comment by mimiblis** [comment]
ohhh I think I understand know... --> need to correct in GTEX_selected-samples_annots.tsv then

**Comment by mimiblis** [comment]
bon je vais essayer de corriger ce fichier. je vais repasser au travers de tout, en espérant trouver pourquoi certains samples sont doublés et meme pas annotés pareil etc. je vous retiens au courant quand cela est fini (#108)

**Comment by ANiknejad** [comment]
closed so far, on going review_of_GTEx_annotations_FILES by Amina
