### ISSUE TITLE
GTEx replicates

### ISSUE THREAD

**Issue by ANiknejad** [BgeeDB/expression-annotations#82]
Sounds like there are **biological** replicates in GTEx

https://rxtx.isb-sib.ch/index.php/apps/files/?dir=%2FShared%2FGTEx%2Fannotation

'Team removes tissues in batches from donor en bloc and dissects it into aliquots later on the back table.'

Here a file, at the bottom a list of replicates:
https://rxtx.isb-sib.ch/index.php/apps/files/?dir=%2FShared%2FGTEx%2Fannotation

No information about any possible technical replicate

**Comment by mimiblis** [comment]
I had to delete every thing I had done for the replicates, because of this mix of affy and stuff it was all wrong --- > dammmmmnnnn

**Comment by ANiknejad** [comment]
no worries, 'biological replicates' are the default status in Bgee, so even no care to put on that, right Fred?
@fbastian

**Comment by mimiblis** [comment]
youpiiiii first Christmas Present if I dont need to do this hihihi

**Comment by ANiknejad** [comment]
ahahahah...I hope so! ;-)
Fred?

**Comment by fbastian** [comment]
Well, there still seems to be a confusion between technical and biological replicates :p All samples annotated to a same condition and coming from different donors are biological replicates. The question is whether there are technical replicates (I don't think so)

**Comment by ANiknejad** [comment]
no confusion, I guess, just I noticed NO TECHNICAL replicates and proposed to not annotate replicates...

**Comment by ANiknejad** [comment]
if a sample is aliquoted in many small samples before processing and measure, there are biological replicates, as far as I understand, because each measure will be done on a specific (small) samples, even from the same donor...

**Comment by ANiknejad** [comment]
...by opposition to technical replicates:
'the purest form of technical replicate would be when the exact same sample (after all preparatory techniques) is analyzed multiple times.'

which sounds not be the case here in GTEx samples

**Comment by ANiknejad** [comment]
@fbastian 
do you agree with me? See above the last two posts, please

**Comment by fbastian** [comment]
Hmm, tricky. For me they are technical replicates, because the samples come from the same tissue in the same donor. Using different aliquots increase the technical variability, not the biological variability. 
@julien-roux, do you agree?

(of course we could argue that samples don't come from the exact same location in the tissue, but this is even more in the spirit of a biological replicate to me: sampling the biological variability from a given tissue)

**Comment by mimiblis** [comment]
but technical replicates are:
"the purest form of technical replicate would be when the exact same sample (after all preparatory techniques) is analyzed multiple times"
here its not the case...

**Comment by fbastian** [comment]
I could argue that it actually is the *exact* same sample, as it comes from the *exact* same organ and donor. It simply a matter of what you are defining as the "sample", and with which granularity.

Anyway I agree with you, but I think here the intend is to have a technical replicate, not a biological replicate. Let's see what @julien-roux thinks.

**Comment by mimiblis** [comment]
:-) okay I see now

**Comment by julien-roux** [comment]
I agree with @mimiblis and @ANiknejad , 2 samples taken from the same donor and same tissues are biological replicates. If there are 2 biopsies, 2 separate pieces of tissue, which contain different pools of RNA molecules, these are biological replicates. If I understand well this is the case here.
> Hmm, tricky. For me they are technical replicates, because the samples come from the same tissue in the same donor. Using different aliquots increase the technical variability, not the biological variability.
@julien-roux, do you agree?

No this is wrong. Different aliquots are different pieces of tissue right?

> (of course we could argue that samples don't come from the exact same location in the tissue, but this is even more in the spirit of a biological replicate to me: sampling the biological variability from a given tissue).

Yes, so this is biological replication. You seem to say 2 different things in this comment (or I misunderstood)

**Comment by fbastian** [comment]
So, after discussing with @julien-roux: you all are technically correct. My point is that such biological replicates do not capture a biological variation that we are interested in. Therefore I think they should be treated as technical replicates (although, again I'm wrong according to the official definition).

We'll discuss this with Julien tomorrow and make a decision.

**Comment by ANiknejad** [comment]
so, all agree GTEx reports biological replicates only
