### ISSUE TITLE
GTEX, final annotations, tri des affy/rnaseq

### ISSUE THREAD

**Issue by mimiblis** [BgeeDB/expression-annotations#83]
Hi, 
So I have spent time on separating the GTEX samples (only the one we considered as good) into the different experiment type they used:
- I have pushed on the master, in the gtex folder 4 new files:
  - 1 with the affy
  - 1 with the illuminaExome SNP
  - 1 with the illuminaOmni SNP
  - 1 with the RNAseq

I have also allowed myself to push on the master the RNAseq annotations (in rnaSeqLibrary.tsv) all the RNAseq samples --> I have put for all of them the corresponding SRX.

If you want a brief summary, we have, for the samples annotated as "good":
- 5445 samples coming from RNAseq
- 423 samples coming from Affymetrix Experiment
- 117 samples coming from Illumina Exome SNP
- 328 samples coming from Illumina OMNI SNP

I hope there are no samples that I have put twice... If someone could have a look at that... my eyes are getting crossed...
++ I haven't done the replicates numbering yet (had to delete all because of this ******* mix of experiment), so I will do next week.

Hope this work is satisfying for you ;-)

++++GTEX_toRNAseq branch is now OBSOLETE!!!!!!!! --> @fbastian : can you remove it?

**Comment by ANiknejad** [comment]
Hello Angélique,

Good job indeed.
I wonder if you could provide a separate RNASeq sample list (5445 samples coming from RNAseq) with the original GTEx Uberon mapping? (from file https://github.com/BgeeDB/expression-annotations/blob/master/annotations/gtex/GTEx_Sample_annot.tsv)

It will gives us a clear idea of the work done by Bgee compared to GTEx. 

For instance
GTEX-U3ZN-1126-SM-4DXUL was GTEx annotated UBERON:0003889  fallopian tube, while Bgee annotation is UBERON:0001302	right uterine tube

**Comment by mimiblis** [comment]
yes, okay I will do that in the current week. You only need this for RNAseq right?

**Comment by ANiknejad** [comment]
yes, because as far as I understood, it will be the only GTEx data released by Bgee pipeline currently

**Comment by ANiknejad** [comment]
and see also #84

**Comment by mimiblis** [comment]
okay

**Comment by fbastian** [comment]
@ANiknejad: why not including already Affy annotations, as they are done?

**Comment by ANiknejad** [comment]
see issue #43 
we do not process the Affymetrix chip used  by GTEx, right?
http://www.ebi.ac.uk/arrayexpress/experiments/E-GEOD-45878/?query=HuGene11stv1_Hs_ENSG

**Comment by fbastian** [comment]
@smoretti will download one of their CEL files (see `GSE45878_RAW.tar` listed at http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE45878), and see if our pipeline manages to automatically download their custom CDF file.

It seems that this chip type is listed in Bioconductor, and could therefore be used (see http://bioconductor.org/packages/release/data/annotation/).

**Comment by ANiknejad** [comment]
@fbastian 
could you please confirm that the rules are: 
if a chip type is listed in Bioconductor, we can **usefully** annotate  it ?

**Comment by fbastian** [comment]
@ANiknejad: yes.

**Comment by ANiknejad** [comment]
closed so far
