### ISSUE TITLE
sample GTEX-14ICL-1826-SM-5RQIY

### ISSUE THREAD

**Issue by ANiknejad** [BgeeDB/expression-annotations#84]
Hi,

I propose to remove/comment (= status 'NO') this sample annotated on UBERON:0002060	femoral artery, because this is the only one artery tissu sample in all GTEx with pathologist's note 'femoral', while the GTEx target in the harvesting instructions is 'artery tibial'.
(femoral artery is used anyway in GTEx to collect blood)

Thoughts?

**Comment by ANiknejad** [comment]
see also new file 
annotations/gtex/Bgee_annotation_versus_GTEx.tsv

The file 'Bgee_annotation_versus_GTEx.tsv' lists the terms used only by Bgee and the terms used only by GTEx in the final master/annotations/rna_seq/RNASeqLibrary.tsv.
At the bottom of the list, terms used by both are shown.
I will review and comment all the terms to be sure we did adequate changes

**Comment by fbastian** [comment]
Why discarding this sample? Even if it is the only one, it's worth it, isn't it?

**Comment by ANiknejad** [comment]
...because I am not sure it is correct or not...'femoral' versus 'tibial'. 
The target here for artery tissue should be 'tibial' following GTEx instructions, and maybe the guy just before has sampled blood from femoral and reported femoral too for the artery sample...who knows? and because this is the only artery sample from 'femoral' instead of 'tibial' I would prefer to discard

**Comment by fbastian** [comment]
OK, please indicate clearly the reasons for discarding in the annotation file (or link to this issue)

**Comment by ANiknejad** [comment]
@mimiblis 
would you do it? please let me know

**Comment by mimiblis** [comment]
I saw that @ANiknejad already trashed this sample, I just explained a little bit why in the file samples_track.tsv
