### ISSUE TITLE
Bgee ERRORs  !!

### ISSUE THREAD

**Issue by ANiknejad** [BgeeDB/expression-annotations#85]
"OK", 21.12.15, ANE

GTEX-111FC-3126-SM-5GZZ2
original information is
Cerebral frontal pole -right     Brain - Cortex
annotated by GTEx and Bgee on UBERON:0001870	frontal cortex

but we should report/annotate on UBERON:0002810   right frontal lobe

see issue #75 my comments 16 november

**Comment by mimiblis** [comment]
Oh nice issue! hehehe. Once I have corrected the things I will put a "OK" at the beginning of the comment  I corrected, otherwise it's gonna be messy as well for you as for me XD

**Comment by ANiknejad** [comment]
you also have to report the infoOrgan as 'Cerebral frontal pole-right'

**Comment by ANiknejad** [comment]
There are many others....

**Comment by mimiblis** [comment]
oui, j'étais justement pile poile en train de checker ça ;-)

**Comment by ANiknejad** [comment]
;-)
merci Angélique!

**Comment by mimiblis** [comment]
Note to myself:

- at the end correct the gtex\final_annotations_categorized_by_type_of_ex\rnaseqGTEX_SRX.tsv, to make it as acurate as rnaseq.tsv
- when all annotations ok, do a file with GTEx Uberon and BGEE uberon terms to have a comparison

**Comment by ANiknejad** [comment]
Are all original information for 'cerebral frontal pole' correctly reported in the Bgee annotation file? Did you manage to find out the issue, means, why the original information was not correctly reported? Please document it!

**Comment by ANiknejad** [comment]
Which 'file is available' and where?

**Comment by mimiblis** [comment]
Euhm thé file with the correspondance uberon gtex - bgee is available... as aked.
Cérébral frontal pole is ok --> was corrected for gtex

**Comment by ANiknejad** [comment]
ok but what is the name of this file and where is this file? (path)
and my question was: what was the problem for cerebral frontal pole not correctly reported from the GTEx original file? Due to wrong manual copy/paste? Or bug in an automatic script?

**Comment by mimiblis** [comment]
path is:  expression-annotations/annotations/gtex/uberon_GTEx_Bgee.tsv
GTEX annotated as UBERON:0001870 ! frontal cortex and after we had discussed these samples we decided to annotate on UBERON:0002810 ! right frontal lobe, because they precised 'Cerebral frontal pole -right', so we could annotate more "pointu" than they did

**Comment by ANiknejad** [comment]
ok, great, many thanks Angélique
