### ISSUE TITLE
GTEx target 'Kidney Preferred Location: Left cortex'

### ISSUE THREAD

**Issue by ANiknejad** [BgeeDB/expression-annotations#87]
we currently have 16 Bgee annotation on UBERON:0000082	adult mammalian kidney
due to discussion in issue #74 
and due to the fact that we noticed some discrepancy in kidney sample collection, with some samples containing both cortex (the target) and medulla tissues.
Here the list of the currently UBERON:0000082 adult mammalian kidney Bgee annotated samples:

GTEX-UPIC-1126-SM-4IHLO
GTEX-ZYT6-2226-SM-5GIC9
GTEX-NPJ8-2226-SM-3TW8D
GTEX-ZC5H-1726-SM-5HL7X
GTEX-WI4N-2026-SM-4OOS7
GTEX-13OVL-1826-SM-5KLZR
GTEX-T6MN-1826-SM-5CHQB_rep1
GTEX-RN64-1626-SM-48FD7
GTEX-ZYFD-1526-SM-5NQ7T
GTEX-XPVG-0526-SM-4B65N
GTEX-N7MS-1626-SM-3LK5F
GTEX-1497J-0826-SM-5NQAJ
GTEX-11OF3-1326-SM-5N9FJ
GTEX-Y5V6-2026-SM-5IFHO
GTEX-P4QS-1126-SM-3NMD5
GTEX-12696-0926-SM-5FQTV

However among this list, 12 samples are in fact correctly 'left cortex' sampled, while 1 sample is correctly 'cortex' sampled but from the right kidney

the list of the correctly 'left cortex' harvested samples:

PLEASE ANNOTATE on UBERON:0001225 cortex of kidney

GTEX-NPJ8-2226-SM-3TW8D
GTEX-ZC5H-1726-SM-5HL7X
GTEX-13OVL-1826-SM-5KLZR
GTEX-T6MN-1826-SM-5CHQB_rep1
GTEX-RN64-1626-SM-48FD7
GTEX-XPVG-0526-SM-4B65N
GTEX-N7MS-1626-SM-3LK5F
GTEX-1497J-0826-SM-5NQAJ
GTEX-11OF3-1326-SM-5N9FJ
GTEX-Y5V6-2026-SM-5IFHO
GTEX-P4QS-1126-SM-3NMD5
GTEX-12696-0926-SM-5FQTV

The 'right cortex' harvested sample:
GTEX-UPIC-1126-SM-4IHLO

PLEASE ANNOTATE on UBERON:0001225 cortex of kidney

**Comment by mimiblis** [comment]
DONE: master 96b61bd

**Comment by ANiknejad** [comment]
thank you, fine!
