### ISSUE TITLE
sample GTEX-Y5V5-1826-SM-4VDS5, please correct the 'infoOrgan'

### ISSUE THREAD

**Issue by ANiknejad** [BgeeDB/expression-annotations#88]
RNASeqLibrary.tsv

please replace - for this sample only - infoOrgan 'Nodular mucosa and submucosa of most distal ileum'

by 

'small intestine-curved portion of colon above rectum'
(the information such as available in the original file)

**Comment by mimiblis** [comment]
DONE: master 47505cd

**Comment by ANiknejad** [comment]
en fait c'est quand tu commit qu'il faut mettre le #88 dans le commentaire du commit, c'est comme ca que après on peut accéder au commit depuis l'issue, sinon comme ici ca tourne en rond (l'issue renvoie sur l'issue)

**Comment by ANiknejad** [comment]
par exemple dans #90 

ANiknejad referenced this issue from a commit a day ago
	@ANiknejad 	column name modification …

following Julien's proposition #90

**Comment by ANiknejad** [comment]
par exemple dans l'issue 90 tu verras un exemple

ANiknejad referenced this issue from a commit a day ago
 column name modification …

following Julien's proposition

**Comment by mimiblis** [comment]
Oui quand il dit mimiblis referenced this issue from à commit c'est que dans le commit j'ai mis le nom de l'issue.  Et dans l'issue j'ai essayé mais raté de mettre le hash du commit

**Comment by mimiblis** [comment]
Ha mais j'ai compris... au lieu de mettre #88 dans le commit je devrais genre mettre correction intestin... oups desolee

**Comment by ANiknejad** [comment]
tu dois mettre #88 dans la description du commit, pas dans le titre

**Comment by mimiblis** [comment]
Euh... ??? Moi je fais gît commit -m 'blabla' je savais pas que y avais une nuance avec ça.  @fbastian: je fais la commande juste?

**Comment by ANiknejad** [comment]
ahahaha...moi depuis mon interface j'ai un summary de commit et une description, et je mets la reference de l'issue dans la description

**Comment by ANiknejad** [comment]
http://stackoverflow.com/questions/16122234/how-to-commit-a-change-with-both-message-and-description-from-the-command-li


réponse ici ;-)

**Comment by mimiblis** [comment]
Windows ça a des avantages hihi. Okay serai prudente dorénavant avec mes commit ;-)
