### ISSUE TITLE
sample GTEX-ZA64-1226-SM-5HL7B, please correct the 'infoOrgan'

### ISSUE THREAD

**Issue by ANiknejad** [BgeeDB/expression-annotations#89]
RNASeqLibrary.tsv

please replace - for this sample only - infoOrgan 'Nodular mucosa and submucosa of most distal ileum'

by 

'small intestine-transverse-ileal mucosa'

**Comment by ANiknejad** [comment]
....note the discrepancy....ileal mucosa can not be 'transverse' in fact, because transverse usually refers to large intestine...

**Comment by ANiknejad** [comment]
maybe to discard this sample?
@fbastian

**Comment by mimiblis** [comment]
DONE: master 30df042
tell me if I need to discard the sample or not

**Comment by ANiknejad** [comment]
ca a l'air d'etre ici qu'il y a eu un problème non? le fichier était completement modifié alors qu'il y avait juste une ligne à remplacer

**Comment by ANiknejad** [comment]
yes, please discard (= commit and explain why) this sample
Could you please explain how you will do that: to comment line (#) in RNASeqLibrary.tsv + to put NO in sample track?

**Comment by mimiblis** [comment]
Okay no problem :-(

**Comment by ANiknejad** [comment]
non mais je te demande (avec le sourire ;-) de me dire ce que tu fais concretement quand tu discardes 'après coup' (comme ici) un sample, c'est à dire quel(s) fichier(s) tu modifies?

**Comment by ANiknejad** [comment]
on est dans du 'après coup' parce que ce sont des décisions de nettoyage qui surviennent après le process de check for subject and sample normality, tu vois ce que je veux dire?

**Comment by mimiblis** [comment]
OuI je vois pas de soucis. ;-) hihihi.

**Comment by mimiblis** [comment]
This sample was discarded (e.g. I # the sample in rnaseqlibrary.tsv + put a quick explanation at the end of the line, AND I passed the sample as NO in the samples_track.tsv, with a similar explanation --> all explanations are related to this issue, so that it's easier to track)

**Comment by ANiknejad** [comment]
Great, many thanks!
