### ISSUE TITLE
headers of RNASeqLibrary.tsv and RNASeqExperiment.tsv

### ISSUE THREAD

**Issue by julien-roux** [BgeeDB/expression-annotations#90]
I noticed quite a few inconsistencies within and between the headers of these 2 files. These include the use of lower/upper/camel case, the use of spaces, etc

`RNASeqLibrary.tsv` current header:
`"#Chip ID"	"Experiment ID"	"chipTypeId"	"organId"	"organName"	"UberonId"	"UberonName"	"stageId"	"stageName"	"infoOrgan"	"infoStage"	"sampleTitle"	"sampleSource"	"SampleDescription"	"SampleCharacteristics"	"organAnnotationStatus"	"organBiologicalStatus"	"stageAnnotationStatus"	"stageBiologicalStatus"	"sex"	"strain"	"TaxID"	"comment"	"annotatorId"	"lastModificationDate"	"replicate"	"infoReplicate"	`

`RNASeqExperiment.tsv` current header:
`"#EXPERIMENT_ID"	"EXPERIMENT_NAME"	"EXPERIMENT_DESCRIPTION"	"EXPERIMENT_SOURCE"	"EXPERIMENT_STATUS"	"COMMENT"`

As I'm modifying the script reading these files, it would be a good opportunity to make these changes. I suggest: 

New `RNASeqLibrary.tsv` header:
`"#libraryId"	"experimentId"	"chipTypeId"	"organId"	"organName"	"uberonId"	"uberonName"	"stageId"	"stageName"	"infoOrgan"	"infoStage"	"sampleTitle"	"sampleSource"	"sampleDescription"	"sampleCharacteristics"	"organAnnotationStatus"	"organBiologicalStatus"	"stageAnnotationStatus"	"stageBiologicalStatus"	"sex"	"strain"	"taxId"	"comment"	"annotatorId"	"lastModificationDate"	"replicate"	"infoReplicate"	`

New `RNASeqExperiment.tsv` header:
`"#experimentId"	"experimentName"	"experimentDescription"	"experimentSource"	"experimentStatus"	"comment"`

What do you think? If we all agree, @ANiknejad could you make the changes? @fbastian: on which branch should we make the changes?

**Comment by ANiknejad** [comment]
please check with @smoretti 
he already uses these column names as it

**Comment by julien-roux** [comment]
If I understand correctly you mean that @smoretti scripts would be affected by the changes?
This is not a problem since I am currently modifying these scripts. @smoretti is there any other script or pipeline step that could be affected?

**Comment by julien-roux** [comment]
And BTW, I think taxID should be replaced by speciesId to be consistent with the database schema

**Comment by smoretti** [comment]
I don't think there is any other script that could be affected as we have removed most intermediary steps

**Comment by ANiknejad** [comment]
ok, so I will do changes in column names here as suggested by Julien if both of you agree ;-)

**Comment by ANiknejad** [comment]
Done, please let me know if you want other changes

**Comment by julien-roux** [comment]
Yes, one last change if @fbastian agrees: `taxID` should be replaced by `speciesId` in RNASeqExperiment.tsv header

**Comment by ANiknejad** [comment]
(Please do not consider the reference above (github does not allow to remove it once created))

**Comment by ANiknejad** [comment]
waiting for @fbastian agreement, as asked by Julien in previous post...

**Comment by ANiknejad** [comment]
@julien-roux 
may I have to change header lines in Affy files too??

**Comment by fbastian** [comment]
OK, I agree with the proposed changes.

@julien-roux, do you want also to take care of the Affymetrix header?

**Comment by julien-roux** [comment]
So far Affymetrix, new headers should be:
`affymetrixChip.tsv`:
"#**chipId**"	"**experimentId**"	"chipTypeId"	"normalizationTypeId"	"detectionTypeId"	"anatEntityId"	"organName"	"**u**beronId"	"**u**beronName"	"stageId"	"stageName"	"infoOrgan"	"infoStage"	"sampleTitle"	"sampleSource"	"**s**ampleDescription"	"**s**ampleCharacteristics"	"organAnnotationStatus"	"organBiologicalStatus"	"stageAnnotationStatus"	"stageBiologicalStatus"	"sex"	"strain"	"*speciesId**"	"comment"	"annotatorId"	"lastModificationDate"	"replicate"	"infoReplicate"

`microarrayExperiment.tsv`
**"experimentId"	"experimentName"	"experimentDescription"	"experimentIdSource"	"experimentStatus"	"comment"	

`chipType.tsv`
"#chipTypeId"	"chipTypeName"	"speciesId"	"**ensemblXrefTable**"	"**c**omment**~~s~~**"

**Comment by ANiknejad** [comment]
@julien-roux 
done

**Comment by julien-roux** [comment]
I've just noticed that the same changes need to be applied to headers of the files `https://github.com/BgeeDB/expression-annotations/blob/master/annotations/rna_seq/Worm/RNASeqLibrary_worm.tsv` and `https://github.com/BgeeDB/expression-annotations/blob/master/annotations/rna_seq/Worm/RNASeqExperiment_worm.tsv`

**Comment by ANiknejad** [comment]
>New RNASeqExperiment.tsv header:
"#experimentId" "experimentName" "experimentDescription" "experimentSource" "experimentStatus" "comment"

"experimentSource"

should be 

"experiment**Id**Source", right? ("i" uppercase, I know!)

to be consistent with

>microarrayExperiment.tsv
"experimentId" "experimentName" "experimentDescription" "experimentIdSource" "experimentStatus" "comment"

@julien-roux

**Comment by ANiknejad** [comment]
Julien, please check the previous comment and the commit I did just now, hope this is fine
@julien-roux

**Comment by julien-roux** [comment]
Thanks for this!

- I think the field should be "experimentSource" and not "experimentIdSource"

- In the commit of `expression-annotations/annotations/affymetrix/Worm/affymetrixChip_worm.tsv`, please revert back from "platform" to "chipTypeId"

**Comment by ANiknejad** [comment]
>I think the field should be "experimentSource" and not "experimentIdSource"

but anyway should be the same for Affy and RNA, right?
Because currently I did the same for both ("experimentIdSource")


>In the commit of expression-annotations/annotations/affymetrix/Worm/affymetrixChip_worm.tsv, please revert back from "platform" to "chipTypeId"

done

**Comment by julien-roux** [comment]
> >  I think the field should be "experimentSource" and not "experimentIdSource"

> but anyway should be the same for Affy and RNA, right?
Because currently I did the same for both ("experimentIdSource")

Yes this field name should be the same in the 4 files (affy worm / affy non worm / RNA-seq worm / RNA-seq non worm)

**Comment by ANiknejad** [comment]
done

**Comment by julien-roux** [comment]
Thanks!
