### ISSUE TITLE
UBERON:0007232 2 cell stage

### ISSUE THREAD

**Issue by ANiknejad** [BgeeDB/expression-annotations#93]
to check name in all our annotation files

**Comment by mimiblis** [comment]
will be done after GTEx is finished if ok, and update me if someone does it inbetween, so I remove it from my TODO's

**Comment by mimiblis** [comment]
- no occurence in affychip.tsv
- corrected in rnaseqlibrary.tsv

**Comment by ANiknejad** [comment]
fine, ok, thank you
