### ISSUE TITLE
UBERON:0007233 4 cell stage

### ISSUE THREAD

**Issue by ANiknejad** [BgeeDB/expression-annotations#94]
to check name in our annotation files

**Comment by mimiblis** [comment]
will be done after GTEx is finished if ok, and update me if someone does it inbetween, so I remove it from my TODO's

**Comment by mimiblis** [comment]
- no occurence in affychip.tsv
- corrected in rnaseqlibrary.tsv

**Comment by ANiknejad** [comment]
only one correction for this name in rnaseqlibrary.tsv?

**Comment by mimiblis** [comment]
Yes that is the only one my searcher found

**Comment by ANiknejad** [comment]
ok,checked,  thank you Angélique
