### ISSUE TITLE
UBERON:0018241 prime adult stage

### ISSUE THREAD

**Issue by ANiknejad** [BgeeDB/expression-annotations#95]
to check stage name in all our annotation files

**Comment by mimiblis** [comment]
will be done after GTEx is finished if ok, and update me if someone does it inbetween, so I remove it from my TODO's

**Comment by mimiblis** [comment]
- no occurence in affyChip.tsv
- corrected in rnaseqlibrary.tsv

**Comment by ANiknejad** [comment]
checked, ok, thank you Angélique!
