### ISSUE TITLE
UBERON:0000104 life cycle

### ISSUE THREAD

**Issue by ANiknejad** [BgeeDB/expression-annotations#96]
please check stage name in all our annotation files

**Comment by mimiblis** [comment]
will be done after GTEx is finished if ok, and update me if someone does it inbetween, so I remove it from my TODO's

**Comment by mimiblis** [comment]
- corrected in rnaseqlibrary.tsv
- no occurence in affyChip.tsv

**Comment by ANiknejad** [comment]
thank you, fine
