### ISSUE TITLE
Mistake in platform? 

### ISSUE THREAD

**Issue by julien-roux** [BgeeDB/expression-annotations#98]
For all libraries of experiment `GSE30617`, the platform (ex-chipTypeId) is annotated as `Illumina Genome Analyzer II`, while from the SRA database, it seems to be `Illumina Genome Analyzer`.
Please verify and correct if necessary. If SRA is wrong, do not change the annotation.

**Comment by julien-roux** [comment]
Same thing for library `SRX323031`, the platform is not matching between the annotation file `Illumina Genome Analyzer IIx` and the SRA record `Illumina HiSeq 2000`.

**Comment by julien-roux** [comment]
Same problem for libraries `SRX018864`, `SRX018865`, `SRX018866` and `SRX018867`: the platform is not matching between the annotation file [Illumina Genome Analyzer II] and the SRA record [Illumina Genome Analyzer].

**Comment by ANiknejad** [comment]
http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE30617
Illumina Genome Analyzer II (Mus musculus)
then correctly reported from GEO (the data information source)

**Comment by julien-roux** [comment]
Same problem for `SRX1125066`: the platform is not matching between the annotation file [Illumina HiSeq 2000] and the SRA record [Illumina MiSeq].

**Comment by ANiknejad** [comment]
https://trace.ddbj.nig.ac.jp/DRASearch/study?acc=SRP002254
--> follow GEO link (bottom of the page)
http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE20348
--->Illumina Genome Analyzer II (Drosophila melanogaster)

**Comment by julien-roux** [comment]
http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE20348
Actually from the name of the samples:
SRX018867 / GSM515637: Head_Dmel_Male (GA I)
SRX018866 / GSM515636: Head_Dmel_Female (GA I)
--> Illumina Genome Analyzer

And: 
SRX018865 / GSM509822: Head_Dmel_Male (GA II)
SRX018864 / GSM509821: Head_Dmel_Female (GA II)
--> Illumina Genome Analyzer II

**Comment by ANiknejad** [comment]
Anyway
http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE20348
only reports one plateform
Platforms (1) 	
GPL9061 	Illumina Genome Analyzer II (Drosophila melanogaster)

and we use this information for data annotation

**Comment by mimiblis** [comment]
so do I need to correct something here?

**Comment by julien-roux** [comment]
For GSE20348, not clear. Both GEO and SRA are apparently to be wrong. @fbastian what do you suggest? I think we should correct since sometimes the info from these repositories will be wrong, and we will get additonal info from the auhtors, the publication, etc

**Comment by ANiknejad** [comment]
@smoretti 
good luck on Monday ;-)

**Comment by ANiknejad** [comment]
https://trace.ddbj.nig.ac.jp/DRASearch/experiment?acc=SRX1125039
--->https://trace.ddbj.nig.ac.jp/DRASearch/sample?acc=SRS1017181
---> SRS1017181 in the original GTEx file here below:

RNA-Seq	<not provided>	SAMN03878016	THE BROAD INSTITUTE	0	PAIRED	<not provided>	Sep 11, 2015	64	33	Oct 06, 2015	SRR2135329	SRS1017181	GTEX-T5JW-1426-SM-5CHRI_rep1	RNA:Total RNA	Esophagus - Muscularis	1664035	706552	Esophagus	No	RNA_Seq (NGS)	female	GTEX-T5JW-1426-SM-5CHRI_rep1	GTEX-T5JW	PRJNA75899	GRU	Homo sapiens	ILLUMINA	SRP012682	<not provided>	<not provided>	phs000424	1	<not provided>	Cross-Sectional	Genotype-Tissue Expression (GTEx)	GTEx

**Comment by ANiknejad** [comment]
Check of the issue, experiment GSE30617:
http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE30617
--> link to:
http://www.sanger.ac.uk/science/data/mouse-genomes-project
--> link to the paper:
http://europepmc.org/abstract/MED/21921910
--> link to suppl. data:
http://europepmc.org/articles/PMC3276836/bin/NIHMS40894-supplement-Supplementary_Information_1.docx
---> we retrieve this information:
"For each strain we generated a mixture of “no-PCR” and double size selected libraries for sequencing on the illumina GAIIx sequencing platform as described previously 1. "

Conclusion: we consider here GEO information as correct, no change done

**Comment by ANiknejad** [comment]
julien-roux commented 6 days ago

Same problem for library SRX323031, the platform is not matching between the annotation file [Illumina Genome Analyzer IIx] and the SRA record [Illumina HiSeq 2000].

*********************************************************************
This is a Bgee annotation error, correction done see commit
http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM1186463
--> Illumina HiSeq 2000
Conformated by the paper:
http://www.nature.com/neuro/journal/v16/n10/full/nn.3512.html

"Cluster generation and sequencing-by-synthesis (36 bp) was performed using the Illumina Genome Analyzer IIx according to standard protocols of the manufacturer, with the exception of one sample (Spd−, 3 day, rep 2), which was sequenced on an Illumina HiSeq 2000. "

**Comment by ANiknejad** [comment]
julien-roux commented 6 days ago

Same problem for libraries SRX018864, SRX018865, SRX018866 and SRX018867: the platform is not matching between the annotation file [Illumina Genome Analyzer II] and the SRA record [Illumina Genome Analyzer].

******************************************************************
All these libraries are available from 2 GEO experiments:
GSE20348 	mRNA-Seq of head tissue from Drosophila melanogaster
GSE44612 	Comparative Validation of the D. melanogaster Encyclopedia of DNA Elements Transcript Models

but only refer to one paper that does not provide precise platform information...
http://genome.cshlp.org/content/24/7/1209.long#sec-18

"We generated RNA reads on the Illumina platform."

Thoughts?
@julien-roux

**Comment by ANiknejad** [comment]
@mimiblis 
I checked/corrected here non-GTEX experiment, please do corrections for the GTEx, many thanks

**Comment by julien-roux** [comment]
> julien-roux commented 6 days ago
> > Same problem for libraries SRX018864, SRX018865, SRX018866 and SRX018867: the platform is not matching between the annotation file [Illumina Genome Analyzer II] and the SRA record [Illumina Genome Analyzer].

> All these libraries are available from 2 GEO experiments:
> GSE20348 mRNA-Seq of head tissue from Drosophila melanogaster
> GSE44612 Comparative Validation of the D. melanogaster Encyclopedia of DNA Elements Transcript Models
> but only refer to one paper that does not provide precise platform information...
> http://genome.cshlp.org/content/24/7/1209.long#sec-18
> "We generated RNA reads on the Illumina platform."

> @julien-roux
> Do you want me to correct by the library name, as you suggested in the post above?

Yes, please correct SRX018866 and SRX018867 platform to `Illumina Genome Analyzer`. I have already added corresponding lines to the `RNASeqLibraryPlatformChecks.tsv` file.

**Comment by mimiblis** [comment]
@ANiknejad and @julien-roux : GTEx samples mentionned above are corrected for the platform illumina MiSeq in rnaSeqLibrary.tsv

**Comment by julien-roux** [comment]
Thanks!
Still left in this issue: https://github.com/BgeeDB/expression-annotations/issues/98#issuecomment-170579093 and https://github.com/BgeeDB/expression-annotations/issues/98#issuecomment-170868166
@mimiblis can you take care of it? Then you can close the issue.

**Comment by mimiblis** [comment]
Done for #98 (comment)
done for #98 (comment)

**Comment by fbastian** [comment]
Thanks a lot @julien-roux

**Comment by ANiknejad** [comment]
now to close ;-)

**Comment by mimiblis** [comment]
mon dieu, je me demande vraiment pourquoi mon open office fait à chaque fois du chni avec ces signes bizarres :'-(

**Comment by ANiknejad** [comment]
oui il faut qu'on checke ca une bonne fois pour toutes, mais ne t'en fais pas! Bisous!
