### ISSUE TITLE
!! Problems between open office and Excel!!

### ISSUE THREAD

**Issue by mimiblis** [BgeeDB/expression-annotations#99]
Hi, 
I do not know if it is Excel's fault but, this morning, when I opened the RNAseqLibrary.tsv file in openOffice, I get really weird stuff...
And this is not the first time that if someone uses excel and saves the file, excel does its own pretty damn things...
So I think that for modifying the tsv, we should all use open office, so that it does not appear anymore that we have these kind of stuff..
Maybe its not excel..., but the last time I check the file, it was ok
![capture du 2016-01-05 12 19 27](https://cloud.githubusercontent.com/assets/13200045/12113950/9cb48f4c-b3a6-11e5-9ebb-d0a86c088195.png)

**Comment by ANiknejad** [comment]
maybe me, but when I checked the commit last time, everything was OK. It should be possible to track the sh*** changes indeed. By the way, yes, this is something I already reported in previous issue, the display in Excel is different from the one in OpenOffice and usually users look at Excel file, so necessary to have nice display in Excel too

see #79  (last post)

**Comment by ANiknejad** [comment]
...but...Caution, open and edit in OpenOffice is still the necessary way of editing .tsv file! 
What appears in Excel is spaces not cleaned in OpenOffice! So why is your last commit (correcting sh** from EXCEL) having 1,977 additions and 1,977 deletions???

**Comment by mimiblis** [comment]
Because I replacer Â □□ by -
And there are 1977 occurences

**Comment by mimiblis** [comment]
For example pituitary Â□□ entire becomes hopefully pituitary-entire

**Comment by mimiblis** [comment]
Tell me if not... :'-(

**Comment by ANiknejad** [comment]
sounds ok, every things is fine in OpenOffice and Excel display, thank you Angélique. I remember I also cleaned some things like that (Uterus â€“ corpus) but obviously some other were remaining
